### ISSUE TITLE
Chrome button on update page does not take you direct to download page

### ISSUE THREAD

**Issue by BryanCrotaz** [browser-update/browser-update#236]
Chrome's landing page is full of adverts for Chrome addons and games. The download link is small and non-obvious for non-geeks.

We should instead detect desktop/mobile and route the user to either
https://www.google.com/chrome/browser/mobile/
or 
https://www.google.com/chrome/browser/desktop/

**Comment by josselex** [comment]
Thank you! That's a good idea. I will set it to the desktop mode because we only notify desktop browsers at the moment.
