### ISSUE TITLE
Project Spartan

### ISSUE THREAD

**Issue by millermk** [browser-update/browser-update#240]
I know it's very early on in the lifecycle of Project Spartan (the replacement for IE on Windows 10).  But this tool mistakenly identifies it as an out of date version of Chrome.  While not critical at this moment, I expect this is something that would definitely need to be addressed before the launch of Windows 10 this summer.

**Comment by josselex** [comment]
I thought I already included project spartan a week ago. Maybe you get stillt the old javascript file or they changed the user agent identification string again.
Could you tell me what you see at this site:
http://browser-update.org/test.html

**Comment by josselex** [comment]
I think this is already fixed...
