### ISSUE TITLE
compress version

### ISSUE THREAD

**Issue by approached** [browser-update/browser-update#244]
Why you are not use a compress version?

On this file: http://browser-update.org/update.js

And:

By compressing http://browser-update.org/img/small/c.gif 960 bytes (72%) could be saved without losses!

**Comment by josselex** [comment]
There is
http://browser-update.org/update.min.js
I think I will linkt to is by default soon.

Which tool did you use to compress the image?

**Comment by approached** [comment]
You can use: http://www.lcdf.org/gifsicle/

**Comment by josselex** [comment]
@approached 
I could not compress the image further. Not with any of the tools I tried, also not with gifsicle.
