### ISSUE TITLE
Improve documentation for customizing text

### ISSUE THREAD

**Issue by jasonhildebrand** [browser-update/browser-update#245]
Thanks for the great project.  Here is a suggestion to improve the documentation on how to customize the text:

    text: "",                       // custom notification html text.  Optionally include up to two placeholders "%s" 
                                      // which will be replaced with the browser version and contents of the link tag.
                                      // Example: "Your browser (%s) is old.  Please <a%s>update</a>"

**Comment by josselex** [comment]
Great idea. I will change this when I update other localization strings in the next months.
