### ISSUE TITLE
Issues with firefox?

### ISSUE THREAD

**Issue by mkivikoski** [browser-update/browser-update#247]
Hello!

Thanks for the great script! 

I'm having issues with running it in Firefox. I've tried it in version 24 and 10 (downloaded from Firefox) on Mac OSX 10.9.5 (and QA team has tried it on windows), and I can't get it to show.  I've tried both the script provided, and the ng-browser-update (https://github.com/tinesoft/ng-browser-update); and both fail.  With the ng-browser-update if I set ' always-show-bar="true" ', the bar can be seen in Firefox. This leads me to believe the script does work, but isn't being trigger by FF properly. Any ideas?

Thanks!
Mike

**Comment by josselex** [comment]
Hi,
I think it's an issue that you have the cookie set. Delete the browser-update.org cookie and it should show again!
Best,
Thomas
