### ISSUE TITLE
Is it possible to change the url link of the whole div?

### ISSUE THREAD

**Issue by sbha5516** [browser-update/browser-update#250]
Clicking the div inside takes user to browser-update website. I will like it to go to a similar page we are creating for our website. Is that possible?

**Comment by dzymail** [comment]
Yes, i want this too,
browser-update website. very slowly to me, and i have more information show to users.

**Comment by sbha5516** [comment]
I just did a pull request for this

**Comment by dzymail** [comment]
How to use this project code on own site? i just want simplest bar display, and link to a html page?
the browser-update.org too slow. too many infomation.
i downloaded code to my site. enabled php httpd mod_rewrite, set .htaccess file
but only haft page displayed.
