### ISSUE TITLE
Horrible SSL/TLS configuration

### ISSUE THREAD

**Issue by rugk** [browser-update/browser-update#257]
Sorry, but your TLS configuration is horrible.
 From SSLLabs you get an F, which is the worst possible.

https://www.ssllabs.com/ssltest/analyze.html?d=browser-update.org

Please fix this errors by disabling the bad cipher suites. Additionally it would be good to upgrade to a SHA-2 certificate and please always provide Forward Secrecy.
And finally please enable [HSTS] (https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) and if you want to provide a really secure TLS connection finally enable [HPKP] (https://en.wikipedia.org/wiki/HTTP_Public_Key_Pinning).

Good to read: https://community.qualys.com/blogs/securitylabs/2015/06/08/introducing-tls-maturity-model

**Comment by ddanier** [comment]
We now get an A, so I'll set this issue to fixed. As we still support normal HTTP connections we won't add HSTS.

The certificate is due in 4 months, I'll upgrade to SHA2 then.

**Comment by rugk** [comment]
Okay, great! Yes the issue is fixed.
