### ISSUE TITLE
Message is hard to read for people suffering from color blindness

### ISSUE THREAD

**Issue by KopfKrieg** [browser-update/browser-update#263]
The message features (at the moment) a blue background, black as primary text color and red colored links. For people suffering from color blindness the red link is hard to read (or, sometimes, not legible at all). Could this please be changed?

For example, a light grey background with red links and black text would be much better (no colors at all and just different shades of grey eliminate the possibility for color blind people to be not able to read the text at all completely).

**Comment by josselex** [comment]
Where does it have this background? Maybe someone modified it but this if
for sure not the default configuration.

2015-08-15 16:39 GMT+02:00 Florian <notifications@github.com>:

**Comment by KopfKrieg** [comment]
Well, at least for me the blue background appears on every site featuring the update-browser.org-script. For example:

![browser-update.png](https://cloud.githubusercontent.com/assets/5047813/9304868/f547c53a-44ec-11e5-8ec0-78a2a501ffc2.png)

Maybe it's a rendering issue in [otter-browser](http://otter-browser.org)?

**Comment by josselex** [comment]
This seemed to be part of a pull request. I fixed it to be normal again. Check with shift-reload.

**Comment by KopfKrieg** [comment]
Works perfect, thanks.
