### ISSUE TITLE
Microsoft Edge "Outdated"

### ISSUE THREAD

**Issue by mtylerb** [browser-update/browser-update#267]
Microsoft Edge, being the latest browser from Microsoft, should not be listed as "outdated".

**Comment by darkmorpher** [comment]
Sounds like https://github.com/browser-update/browser-update/issues/264

**Comment by josselex** [comment]
Where does is it said that it is outdated?
(which website, which message, ...)

**Comment by josselex** [comment]
Can not reproduce. Closing.
