### ISSUE TITLE
Show is browser IS up to date - Suggestion

### ISSUE THREAD

**Issue by ekazda** [browser-update/browser-update#268]
When a user is sent to https://browser-update.org/update.html, it would be great if it told them that their browser **IS** up to date. It would also be great if the version numbers from the original link were passed into this page so that the browser check used those numbers instead of the defaults.

**Comment by ekazda** [comment]
Just curious if this suggestion was seen and if there were any thoughts on implementing this idea.

**Comment by josselex** [comment]
Indee, the site should show if the browser is up to date.
But I don't understand your part about the original version numbers form the link.
Because if the user gets the notification, his browser will be out of date for sure...

**Comment by ekazda** [comment]
For instance, I have a webpage on a site that checks a users browser with this JS. It also contains a simple button that links to update.html that doesn't run any check at all. It would be nice if, on that button, I could include a link such as https://browser-update.org/update.html?i=9&f=35&o=25&s=7 that would use those perimeters to check the users browser against the desired settings.

**Comment by josselex** [comment]
It is now checked if the browser is up-to-date. 
But I did not implement your suggestion with checking against the versions of the original  link because:
If the browser is out of date and you are already on this site, you should update. And we should not pretend that it IS up-to-date. This would be somehow dangerous.
