### ISSUE TITLE
Changing default appending from 'body' to class element breaks script

### ISSUE THREAD

**Issue by darkmorpher** [browser-update/browser-update#271]
Appending the script (element `#buorg`) to somewhere other than page `body` like class elements, breaks the script.

CC @josselex

**Comment by josselex** [comment]
Hi. What did you exactly do? I cannot reproduce this (I don't know how).

**Comment by darkmorpher** [comment]
On Browser-update.org:
```
<script> 
var $buoop = {c:2}; 
function $buo_f(){ 
 var e = document.createElement("script"); 
 e.src = "//browser-update.org/update.min.js"; 
 document.body.appendChild(e);
};
try {document.addEventListener("DOMContentLoaded", $buo_f,false)}
catch(e){window.attachEvent("onload", $buo_f)}
</script>
```

I **changed** `document.body.appendChild(e)`
to `document.getElementById("content").appendChild(e)`

**Comment by josselex** [comment]
Why do you want to append the script to a different element? This changes nothing. Do you want to append the bar that appears to  another element?

**Comment by darkmorpher** [comment]
Problem is because of sticky [sidebar here](http://darkmorpher.xyz)

Temp fix was to use z-index and some padding.
