### ISSUE TITLE
All of a sudden browser update not working

### ISSUE THREAD

**Issue by PREM25** [browser-update/browser-update#272]
The below code was working fine but all of a sudden stopped working, wondering if there was any updates/changes were made to the base code. The commented code works (just wanted to make sure i was hitting the code), I even tried using the raw code from http://browser-update.org/update.min.js ans assigning it to e.innerHTML and could not get it to work. Any help would be much appreciated.

function $buo_f() {
    	//var test = document.createElement('a");
	//test.href = "http://www.gigadude.com";
	//test.text = "GIGADUDE";
	//document.body.appendChild(test);
    var e = document.createElement("script");
    e.src = "//browser-update.org/update.min.js";
    document.body.appendChild(e);
};
try { document.addEventListener("DOMContentLoaded", $buo_f, false) }
catch (e) { window.attachEvent("onload", $buo_f) }

**Comment by josselex** [comment]
Can you point me to an example website? 
Are you sure you just don't see the bar because it is shown to every user only once? (clear your cookies to see it again)
What does "not working" explicitly mean?

**Comment by PREM25** [comment]
I did clear the cookies and refresh the browser and still didn't work

An example would be:
1) opened a new ASP.Net web project in VS 
2) added the below js code within a script tag under <asp:content> tag in Default.aspx

function $buo_f() {
alert("1");
var e = document.createElement("script");
e.src = "//browser-update.org/update.min.js";
document.body.appendChild(e);
alert("2");
};
try { alert("3"); document.addEventListener("DOMContentLoaded", $buo_f, false); }
catch (e) { alert("4"); window.attachEvent("onload", $buo_f); }

3) launched the app

4) Alert fired in order - (3-1-2)

5) switched the browser (IE) mode to 9 - (3-1-2)

6) refreshed the page - (3-1-2)

4) still could not see the update browser panel

Kindly let me know if any other info is required from my end

**Comment by josselex** [comment]
I guess you have to launch it from a webserver (with http://)
or change the code to e.src = "http://browser-update.org/update.min.js";

Also try to add
var $buoop = {test:true}
and see if you see the bar.

**Comment by PREM25** [comment]
Thanks.....it worked but not as expected.

After I added var $buoop = {test:true} in place of my old code (as below)
the browser update message is highlighted even if I am in IE 11. We need to pop this message only if the user is in IE 9 or less. Guess the browser update is shown as part of setting the attribute to true

OLD CODE
=========
var $buoop = {
		c: 2,
		reminder: 0,
		text: "We are committed to delivering you the best experiences online. <strong>But we noticed that your browser (%s) is out of date and is no longer supported.</strong> We recommend that you <a%s>update your browser</a> for increased security and the best experience",		
		onclick: function () { ga('send', 'event', 'browser-update', 'update browser', 'clicked'); },
		onclose: function () { ga('send', 'event', 'browser-update', 'dismiss reminder', 'clicked'); }
	};

Appending the "http:" protocol or ignoring it in the e.src has no effect. 
We use http & https protocols in our site and works well without appending the protocols

Can you please let me know what went wrong in our custom var $buoop code

**Comment by PREM25** [comment]
Hi there, Sorry for all this trouble, there was some miss config on testing....I did change the document mode but have not changed the user agent string to the appropriate IE version.

Once again thanks for your time and patient in trying to sort this issue out.....
