### ISSUE TITLE
How to show the browser-update plugin in IE 8 & 9 browser alone?

### ISSUE THREAD

**Issue by eswarams** [browser-update/browser-update#275]
Hi,
I tried to implement the browser-update plugin for less than or equal to IE9 browsers only to my website. But I have an issue with customization script. 
var $buoop = {
vs: {i:9}, // Less than IE versions 9
test: true,
text:"<a href='http://windows.microsoft.com/en-IN/internet-explorer/download-ie' target='_blank'>please update your browser</a>"
};

How to add the browser-update plugin for IE browser alone? Because I don't want to add this plugin for other browsers: FF, Chrome, Safari, etc.

Thanks!

**Comment by josselex** [comment]
You could use "conditional comments" (google for it) if you like.
