### ISSUE TITLE
Expected expression, got '<'

### ISSUE THREAD

**Issue by srijken** [browser-update/browser-update#277]
I don't have a lot of info on this one, but this showed up in our Exceptionless.Javascript log. Haven't seen it before, so my guess is that it has been introduced recently. First occurrence was 17 days ago.

    SyntaxError: expected expression, got '<'
      at <anonymous>() in https://browser-update.org/update.min.js:line 2

Firefox 42 on Mac OSX 10
Firefox 41 on Ubuntu

but also without any stack error on Chrome 46:

    SyntaxError: Unexpected token <

We use it with these settings:

    	 var $buoop = {
            c: 2,
            vs: {i:8, f:25, o:12.1, s:7},
            reminder: 1,
            reminderClosed: 1
        };

**Comment by josselex** [comment]
I think we did not change anything back then. And seems to be running ok everywhere else.

**Comment by srijken** [comment]
I guess this is caused by a security proxy server (not sure which one). All failures we're seeing are from a a single customer.
Also, line 2 is reported, but line 2 is just javascript comment in the current version of the file.

    //(c)2015, MIT Style License <browser-update.org/LICENSE.txt>
    //recommended to directly link to this file because we update the detection code

My suspicion at the moment is that the <browser-update.org/LICENSE.txt> thing somehow triggers it. I will try to investigate this further.

**Comment by josselex** [comment]
Ok. I will close the issue since i cannot analyze it further.
