### ISSUE TITLE
Firefox ESR 38.4.0 is shown as out dated

### ISSUE THREAD

**Issue by tommikivi** [browser-update/browser-update#278]
Firefox ESR 38.4.0 is shown as out dated currently with browser-update. Hopefully you could add this to supported browsers soon.

Here are some older tickets concerning older ESR updates:
https://github.com/browser-update/browser-update/issues/226
https://github.com/browser-update/browser-update/issues/181
https://github.com/browser-update/browser-update/issues/162

**Comment by josselex** [comment]
I forgot about it, again. This is fixed since yesterday.
