### ISSUE TITLE
Custom messge (text: "..") only working for some browsers 

### ISSUE THREAD

**Issue by carlovinci17** [browser-update/browser-update#280]
Hello,

I have added your script to our site and have noticed that the custom message only displays for some browsers. All other times the default message is displayed. Do you have any suggestions on how to fix?

I have the main javascrtipt (browser-update.min.js) loading first then the custom variables. 

This is the variable i'e updated. text: "......." 

Thanks,
~ Carlo

**Comment by josselex** [comment]
If you do not load the javascript first, but use the exact code form the site it should work.
