### ISSUE TITLE
FireFox 38 and Safari issues

### ISSUE THREAD

**Issue by taddmencer** [browser-update/browser-update#282]
Using this, the bar appears for FF39 and FF17 but not FF38. 

Safari 6 & 7 on a Mac does not trigger this, but Safari 5 does.

I started using only the c2 setting, but then tried to add the full lines like

    var $buoop = {vs:{i:9,f:38,o:12.1,s:7},c:2};

In order to force it to work, but I'm not getting anywhere. 

I have the following in my global site.js file

    var $buoop = {vs:{i:9,f:38,o:12.1,s:7},c:2};
    function $buo_f(){
     var e = document.createElement("script");
     e.src = "//browser-update.org/update.min.js";
     document.body.appendChild(e);
    };
    try {document.addEventListener("DOMContentLoaded", $buo_f,false)}
    catch(e){window.attachEvent("onload", $buo_f)}

**Comment by josselex** [comment]
What is the user agent string of the safari 6 and 7 browsers that you are using?
FF38 is never notified since it is a Long term support version.

**Comment by josselex** [comment]
I did not get more information on this. closing.
