### ISSUE TITLE
Is browserupdate correctly identifying LTS Firefox?

### ISSUE THREAD

**Issue by roneill12** [browser-update/browser-update#283]
Does browserupdate.org take Long Term Support Firefox versions into account?  I'm seeing users flagged for 38.4 (granted, one minor rev back) as old not because they're running 38.4 instead of 38.5 but because they're running 38.

Is it handling these users correctly, or is it treating LTS as being "old" once the main version increments?

**Comment by josselex** [comment]
In general Firefox version 38 is not notified to avoid notifying LTS users.
