### ISSUE TITLE
Optimize images/icons

### ISSUE THREAD

**Issue by DePalmo** [browser-update/browser-update#288]
Hello.

After I included this plugin into one of my websites and tested it on GTMetrix, I got back poor results because of non-optimized icon image. Could those be optimized? It's actually a simple task of throwing them into www.tinypng.com and re-uploading back to server.

Thank you.

![browser-update 1](https://cloud.githubusercontent.com/assets/3665779/12375247/c913e904-bcb9-11e5-947f-a16db8db0074.JPG)

**Comment by josselex** [comment]
I already tried it with different services, but it did not get better. You can try it if you like.

**Comment by DePalmo** [comment]
Will try, but I don't use GitHub that much so I don't know how to create a Pull Request.

**Comment by DePalmo** [comment]
GitHub doesn't support uploading a ZIP file into messages (despite it claims that it does), so here's a link to compressed images: https://www.dropbox.com/s/8ga1xq0p4k84c9k/browser-update-images.zip?dl=0

Before compression size: cca. 206KB
After compression size: cca. 58KB

I hope you will replace the images, until then I had to remove the code to your plugin.

**Comment by josselex** [comment]
I added your images.

**Comment by josselex** [comment]
Thank you!
