### ISSUE TITLE
Browser-Update Script on Android Tablet Always Detects Browser as: Other

### ISSUE THREAD

**Issue by bfleishman** [browser-update/browser-update#293]
I am running this script on my intranet app and when I browse to the site using my LGVK810 G Pad™ 8.3 LTE-LGVK810 tablet, the script will show that I am using a browser version of **Other**. I have determined this by appending the URL with #test-bu. 

This is observed regardless of which type of browser I use on the tablet, I.E chrome, Firefox or Opera, etc...

Is this normal behavior. Is there something with Android tablets that doesn't allow this script to run correctly?

-Brian

**Comment by josselex** [comment]
We do not yet notify mobile browsers but are working on it.

**Comment by josselex** [comment]
Now we are detection android browsers.
