### ISSUE TITLE
Suggest a portable browser

### ISSUE THREAD

**Issue by dmt0** [browser-update/browser-update#294]
"If you are on a computer that is maintained by an admin and you cannot install a new browser. Consider installing a portable version of the browser: http://portableapps.com/apps/internet"

**Comment by josselex** [comment]
I'm testing it now on the English version page.
http://browser-update.org/en/update.html
I think i will tweak the text and see how many people use the link.

**Comment by josselex** [comment]
This is now also activated for German, because the portable apps site is also available in this language.

Do you know other sources for portable apps available in more languages?

**Comment by josselex** [comment]
For now only active for english and german.
