### ISSUE TITLE
eTags on https://browser-update.org/update.min.js

### ISSUE THREAD

**Issue by codingat4am** [browser-update/browser-update#296]
We noticed eTag is being served on the file 

https://browser-update.org/update.min.js

can you please remove this?

**Comment by josselex** [comment]
Hi,
I can do this. Can you explain why?

**Comment by josselex** [comment]
Can you give me more information on this? And why should they be removed?

**Comment by TPS** [comment]
Because folks are likely to block https://browser-update.org/ via the big tracker blocklists _iff_ they suspect it's being used for cross-site tracking!

**Comment by josselex** [comment]
What does this to do with etags? Sorry, I don't know to much about this.

**Comment by josselex** [comment]
Ok. I read about it. It can be used to do tracking without cookies and has been misused by some websites in the past. 
Now I removed it.

**Comment by TPS** [comment]
@josselex You got lucky.…  You reposted & fixed before [I could get in my snide remark](http://bfy.tw/8Tok)! 😉

Thanks! :bow:
