### ISSUE TITLE
Opera latest version 36.0 not recognised as up to date

### ISSUE THREAD

**Issue by sebpatu** [browser-update/browser-update#297]
Hi,
My Opera version is up to date, on windows 7 x64 but browser-update.org tells me my browser is not up to date.

Version :	36.0.2130.59 - Opera est à jour
Flux de mise à jour :	Stable
Système :	Windows 7 64-bit (WoW64)

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36 OPR/36.0.2130.59

Thanks

**Comment by josselex** [comment]
Hi,
Strange. What do you see here:
http://browser-update.org/test.html

**Comment by josselex** [comment]
And on which site do you get the message.

**Comment by josselex** [comment]
Not enough information. Should work now.
