### ISSUE TITLE
Suggestion for code-based (non-visual) notification only option

### ISSUE THREAD

**Issue by carl87gt** [browser-update/browser-update#299]
Currently, there is an option for onShow callback function which is nice but I really need a predicate function that tells me if they are using a modern browser (true) or not (false). Our team has developed an integrated payments popup plugin that can be implemented on our customer's websites. I don't want to enable our functionality on insecure, older browsers (so I need true to enable or false to disable). 

I can show a message on my embedded popup plugin but I don't want to show a message banner at the top of the host website; it is not my place to tell my customer's customers that they need to upgrade their browser to use their website. I can only tell them they need to update their browser to use my popup plugin functionality. 

I would be happy to explain more or contribute to this project on this request.

**Comment by josselex** [comment]
This is now possible.
Add 
"nomessage: true"
to the options and it will just fire the callback.

See:
http://browser-update.org/customize.html

**Comment by carl87gt** [comment]
Hey, that is fantastic! Thanks!
