### ISSUE TITLE
Wrong Korean translation for update page

### ISSUE THREAD

**Issue by Hoya** [browser-update/browser-update#301]
The translation on the [update browser page](https://browser-update.org/ko/update.html) is inaccurate.

English: "Your browser is **out-of-date**."
What is says in Korean: "Your browser is **up-to-date**."

You're asking people to update their browser but the landing page says the browser is already up to date.

I looked into the latest update.po file and this seems to have already been fixed but has this not been deployed? The message is extremely confusing and needs to be fixed asap.

**Comment by josselex** [comment]
This should be fixed now. Can you check it?

**Comment by Hoya** [comment]
Looks good, great work.
