### ISSUE TITLE
The message showed up for IE9 even though I set the minimum version is IE8.

### ISSUE THREAD

**Issue by lmq009** [browser-update/browser-update#302]
Could you please fix it ?  We don't want it shows up in IE9.

**Comment by FUNimations** [comment]
+1

**Comment by josselex** [comment]
If you use the latest embed code from out site this should work correctly now.

**Comment by lmq009** [comment]
Thank you very much :)

**Comment by lmq009** [comment]
Hello,

It shows the message bar for all Firefox browsers, I didn't set version
check for Firefox.  Could you please take a look ?

Thanks,
Mark

**Comment by josselex** [comment]
Can you send me your configuration code or the site where you have embedded
the code?

2016-10-25 20:54 GMT+02:00 lmq009 <notifications@github.com>:

> Hello,
>
> It shows the message bar for all Firefox browsers, I didn't set version
> check for Firefox. Could you please take a look ?
>
> Thanks,
> Mark
>
>

**Comment by lmq009** [comment]
vs:{i:8}, reminder:2, text:"The version of Internet Explorer you are using
is out of date. To get the best possible experience using our website, we
recommend that you upgrade to a newer version of Internet Explorer, or
choose another web browser."

-----------------------------------------------
I added firefox version to stop it:
vs:{i:8, f:1}


Thanks

**Comment by josselex** [comment]
please add api:4
This makes you use the current api.

Then it will read:
{vs:{i:8,f:1}, reminder:2, text:"...",api:4}

**Comment by josselex** [comment]
please add c:4
This makes you use the current api.

Then it will read:
{vs:{i:8,f:1}, reminder:2, text:"...",c:4}

2016-10-26 22:12 GMT+02:00 lmq009 <notifications@github.com>:

> vs:{i:8}, reminder:2, text:"The version of Internet Explorer you are using
> is out of date. To get the best possible experience using our website, we
> recommend that you upgrade to a newer version of Internet Explorer, or
> choose another web browser."
>
> -----------------------------------------------
> I added firefox version to stop it:
> vs:{i:8, f:1}
>
>
> Thanks
>
>
> On Wed, Oct 26, 2016 at 11:43 AM, josselex <notifications@github.com>
> wrote:
>
> > Can you send me your configuration code or the site where you have
> embedded
> > the code?
> >
> > 2016-10-25 20:54 GMT+02:00 lmq009 <notifications@github.com>:
> >
> > > Hello,
> > >
> > > It shows the message bar for all Firefox browsers, I didn't set version
> > > check for Firefox. Could you please take a look ?
> > >
> > > Thanks,
> > > Mark
> > >
> > >
