### ISSUE TITLE
Close button incompatible with keyboard navigation

### ISSUE THREAD

**Issue by juliemoynat** [browser-update/browser-update#305]
Hi,

Can you use a `<button>`element instead of a`<div>` for the close button ? We can't have focus on a `<div>` and a button should be a button.

I would also tell you that the text should be "Close" instead of "x" because when you are blind, "x" is meaningless. You can mask the text thanks to CSS with "`position:absolute; left:-99999px;`" and put a "`aria-hidden="true"`" around the "x" : 
`<button>
<span style="position:absolute; left:-99999px;">Close</span>
<span aria-hidden="true">x</span>
</button>`

I'll use this plugin for a website that have to respect accessibility rules and this is a problem...

Thankyou!

**Comment by alistaircom** [comment]
I think this is a great idea, although it does change the experience for everyone currently using the software.   

Forgive my ignorance, is there an accessible way that this can be handled without changing the X to the word Close? Just wondering what other strategies are?

**Comment by juliemoynat** [comment]
I've already given you the transparent solution but I will explain it more here.

> You can mask the text thanks to CSS with "`position:absolute; left:-99999px;`" and put a "`aria-hidden="true"`" around the "x" :
`<button> <span style="position:absolute; left:-99999px;">Close</span><!-- using a class on the previous span, of course --> <span aria-hidden="true">x</span> </button>`

--> The text "Close" masked in that way in CSS can be read by screen readers (used by people who are blind or some people with cognitive disabilities for example) but will not be displayed. ("display:none;" can't be read by screen readers)
--> Putting an "`aria-hidden="true"`" around the X allow screen readers to ignore that X and not to pronounced it.
--> Using a `<button>` instead of a `<div>` will make this element focusable and will bring semantics (Screen readers would say "Close button"). You can use `background:transparent; border:0 none;` in CSS to override its button style.

Do you better understand my request?

**Comment by alistaircom** [comment]
My bad, didn't properly read your first comment. Got it now.

**Comment by josselex** [comment]
This is fixed now with having a new design for the bar having a "update browser" and "ignore" button, both implemented as normal links.
