### ISSUE TITLE
IE11 stated as obsolete

### ISSUE THREAD

**Issue by Marie28** [browser-update/browser-update#306]
Hi
Opening a website (teammood), IE11 is shown as obsolete. The proposition is to update to Chrome, Firefox or Edge. I cannot update to Edge as I am in Windows 7.

IE 11 on Windows 7 SP1 is fully supported by Microsoft. Why to say that IE11 is obsolete?

Kind regards
Marie

**Comment by josselex** [comment]
This is because it is a quite old browser (3 years old!) and the website you are visiting may need features of newer browser.
