### ISSUE TITLE
Online version is out of date (Chrome Version)

### ISSUE THREAD

**Issue by erotte** [browser-update/browser-update#309]
The current Chrome version used in the current online version (http://browser-update.org/update.js) is wrong:

`this.op.vsakt={i:12,f:45,o:36,s:9.1,n:20,c:49}`

The proper current Chrome Version at this time is `52.x`, Firefox is at v48. 

I tried the `browsers.py` crawling script from the repo, it detects the correct versions.

```
Firefox has version 48.0
Google_Chrome has version 52.0
Opera_(web_browser) has version 39.0
Safari_(web_browser) has version 9.1
Pale_Moon_(web_browser) has version 26.4
Yandex_Browser has version 16.4
Vivaldi_(web_browser) has version 1.3
Opera_Mobile has version 37.0
Google_Chrome has version 52.0
Firefox_for_mobile has version 48.0
```

This is crucial, because the versions passed through with the `vs:{}` option are checked against the current version, so you cannot check for a version above 49 for Chrome.
  
How often do you update the live version of the script?

regards
Ecki

**Comment by josselex** [comment]
Hi Ecki,
Usually I update this each month. With the crawling script I want to automatize it and do it more frequently.
I will fix the version this week.

Thomas

**Comment by josselex** [comment]
This is fixed now.
