### ISSUE TITLE
Cannot get custom text to render

### ISSUE THREAD

**Issue by alistaircom** [browser-update/browser-update#311]
I have tried a number of methods, including copying directly from the browser-update.org site in an attempt to get the custom text to appear when a browser is out of date.

I'm wondering if I am doing something wrong, or if the message doesn't display in the test version (by appending #test-bu) to the URL.

**Comment by josselex** [comment]
Sorry. There was a Bug. Someone already submitted a fix. I can upload it in
a Week.

Am Freitag, 9. September 2016 schrieb Alistair Calder :

**Comment by josselex** [comment]
The fix is now online!

**Comment by Besttest13** [comment]
Thank you! I see our updates displayed correctly. Appreciate the time and effort. Thanks.
