### ISSUE TITLE
403 error because of cloudflare

### ISSUE THREAD

**Issue by arafays** [browser-update/browser-update#314]
Since your website moved to https from cloudflare I am getting a 403 error when I open any page that has your code in it

**Comment by josselex** [comment]
Can you tell me what browser you are using and an example of a site where this happens?

**Comment by arafays** [comment]
I am using the latest (53.x) chrome browser added an image so that you can see the issue I am facing and here is the website (added specifically this page as this is the cleanest page where there are no other errors)

http://www.bidnessetc.com/company360/

![capture](https://cloud.githubusercontent.com/assets/6192554/19195151/bad80fd8-8cc9-11e6-96a1-8bbfe948d0b4.PNG)

This error is resolved after visiting the browser-update.org and entering the captcha from cloudflare

**Comment by josselex** [comment]
For me it works fine. Maybe it's your configuration or something like this?
I tested in chrome. Can you test it on another machine?

2016-10-07 17:10 GMT+02:00 Abdul-Rafay Shaikh <notifications@github.com>:

**Comment by alistaircom** [comment]
Just tried it myself. Seems to work.
