### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by sinrise** [browser-update/browser-update#315]
Currently, the documentation does not explain all the features and if it does, I couldn't find it.
The one thing I'm trying to figure out is what the option 'c' actually does. It's not obvious, and it's not in the example of how to add options. (not the 'c' inside the 'vs' array, the 'c: 4' line after that array. What is it?

**Comment by josselex** [comment]
I have now renamed the option "c" to "api" and it is now explained on the customize page.
