### ISSUE TITLE
Not notified because: mobile on android

### ISSUE THREAD

**Issue by DuncanRowland** [browser-update/browser-update#317]
The blog posting, September 4th, 2016, says, "Testing update notification for mobile Browsers: Stock Android Browser [...] Now we started to notify users that are using the outdated stock Android browser if they have an upgrade path to another newer browser on their system."

However, when I visit /test.html it says, "Chrome 30 Not notified because: mobile on android"

Why not give the option to direct if detected? In my case, the most recent chrome works fine on my test device (Pixi3), but my app doesn't work with the ancient stock browser, so it'd be great to detect and notify the user (like the blog posts indicates should be happening).
Thanks, -D  

User-Agent-String:Mozilla/5.0 (Linux; Android 4.4.2; en-us; 4009X Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36

Lang: en-US

Detected Browser as:
Chrome 30
Not notified because: mobile on android

**Comment by josselex** [comment]
I will activate the notification for other android browsers in the next days. We just wanted to check first how the update experience is for users coming from mobile android browser.

**Comment by josselex** [comment]
I have now activated notification of outdated chrome/firefox/opera on android.
