### ISSUE TITLE
firing update message on samsung 'internet' browser

### ISSUE THREAD

**Issue by kater89** [browser-update/browser-update#318]
When I have this enabled, the error/update message shows on the default Samsung 'internet' browser

https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser&hl=en

I have temporary fixed this issue by disabling the update / error message on mobile devices but I would like to add that back on.

My code is: vs:{i:9,f:40,o:30,s:7.1,c:44},unsupported:false,mobile:false,c:4 if that helps. 

Is there a version of FF / Opera / Safari etc that is triggering the 'internet' browser to trigger the issue even though it is up to date?

**Comment by kater89** [comment]
note: It looks like it uses "Chromium" which is also what Chrome is based on...

**Comment by josselex** [comment]
Can you post the user agent string of the Samsung Browser?

2016-11-23 19:41 GMT+01:00 kater89 <notifications@github.com>:

**Comment by kater89** [comment]
It is called “Internet” version 4.0.20-68. on a Galaxy Note 6. I don't have the device in front of me to get the full user agent string. 

I also got the same issue when using BrowserStack Samsung devices on the is "internet" browser

**Comment by josselex** [comment]
We now corretly identify and offer updates for "Samsung Internet" -Browser

**Comment by josselex** [comment]
you can configure the version to notify by adding somsung to the version list
 vs:{i:9,f:40,o:30,s:7.1,c:44,samsung:4.0}
