### ISSUE TITLE
Yandex browser support

### ISSUE THREAD

**Issue by XOP** [browser-update/browser-update#319]
[Yandex browser](https://en.wikipedia.org/wiki/Yandex_Browser) is based on Chromium, however when the notification appears ("Your browser Chrome 38 is outdated") it does not make much sense to user, who is not aware of all this nerd stuff.

It would be great to have a separate key for that in the options to distinguish Yandex and Chrome.

**Comment by josselex** [comment]
This was a bug. Now it is correctly detected as Yandex Browser.

**Comment by XOP** [comment]
@josselex could you please link a PR with the fix? I have this problem now with the latest setup

**Comment by josselex** [comment]
Its in the latest commit. You need to shift-reload I guess.

**Comment by XOP** [comment]
👍
