### ISSUE TITLE
Installation needs MySQL?

### ISSUE THREAD

**Issue by helantao** [browser-update/browser-update#321]
Hey, I would like to install browser-update to build a small website for research and learning, please tell me the detailed installation method, thank you very much!

**Comment by alistaircom** [comment]
No need for MySQL, everything works via javascript. [You can find all the details here](http://browser-update.org).

**Comment by helantao** [comment]
I know how to browser-update code into the site...
I just mean that I want to download open source code, the establishment of a similar browser-update.org site, which can study and learn... At the same time, _.htaccess pseudo static rules are used to erect the Apache in server, so how should the rules of the nginx be written? Can you update a pseudo static.Conf that can be used in nginx?

**Comment by josselex** [comment]
You can just omit count.php and you do not need mysql. Its just for tracking the number of installs.
