### ISSUE TITLE
prevent "opener" access to the hosting website

### ISSUE THREAD

**Issue by Jens-G** [browser-update/browser-update#322]
There are some `window.open()` calls in the code that should be improved in  way where "opener" XSS attacks are made impossible. Just in case, someone hacks your site, for sure people don't want to be XSSed that way. That, by the way, is another reason not to hotlink to your script and instead host it on own webspace. 

Keep up the good work!

Further reading:
https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

**Comment by josselex** [comment]
Hi Jens,
I now added rel="noopener" to all target="_blank" links. Except links getting opend by javascript, where this is more complicated to secure.
