### ISSUE TITLE
On landing page, hide unsupported browsers

### ISSUE THREAD

**Issue by jesperronn** [browser-update/browser-update#325]
when completely blocking newest version of a browser like in #323 and #324, it brings up an interesting problem.

If I block Opera by `vs:{o:0}`, and go to http://browser-update.org/update.html

Then Opera is still shown. Is there a setting/flag I can pass to the update.html page in order to only recommend Chrome, for instance?

**Comment by josselex** [comment]
Hi Jesper,
Indeed blocking browsers completely is a problem. And it is not recommended at not the purpose of the project. However, one may add this feature with a big warning label for people who want to use this. Maybe with a flag to make sure that people are really aware what they are doing.. And one also would need to change the message shown in the bar and on the update page, along with the the issues in this bug report.
Possible message: "Your browser is not supported on this page, we recommend you to use an additional other browser for the best experience on this page".
