### ISSUE TITLE
Not possible to point at local url for "update your browser" link

### ISSUE THREAD

**Issue by jesperronn** [browser-update/browser-update#326]
From the documentation:

```
    url: null,                      // the url to go to after clicking the notification
```
However, I cannot put in `http://my.custom.site.com/browser_support`

It seems that this line overrides whichever `url` parameter that is set.

https://github.com/browser-update/browser-update/blob/bf190fc4425044648990ae2de335e4eef1730491/update.show.js#L12

Is this on purpose? 

If so, I cannot use the script on my site, since my browsersupport message will be completely different.

**Comment by jesperronn** [comment]
Workaround configuration:

```
url: '/my_browser_support_page',
onclick: function(e){console.log('click',e); e.preventDefault();},
```

**Comment by josselex** [comment]
Indeed, this is a bug. I will fix it the next days.

**Comment by josselex** [comment]
I fixed it now. Can you validate the fix?
