### ISSUE TITLE
browser-update.org/update.show.min.js does not appear to have 'en' key

### ISSUE THREAD

**Issue by CrashyBang** [browser-update/browser-update#329]
The current `browser-update.org/update.show.min.js` that is being inserted does not appear to have an `en` key and as such is failing with the following error:

```
Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at $buo_show (update.show.min.js:1)
    at update.show.min.js:1
```

**Comment by josselex** [comment]
I fixed it. Thanks for reporting!
