### ISSUE TITLE
full URLs in update.min.js

### ISSUE THREAD

**Issue by marathia** [browser-update/browser-update#331]
It would be great if the URLs in update.min.js were written as **http:**//browser-update.org/etc instead of //browser-update.org/etc

That would make it possible to test and adjust the script locally, not only online.

**Comment by josselex** [comment]
fixed in commit 0cfbd3f

**Comment by marathia** [comment]
Sorry to reopen this, but I found one more in update.show.min.js:

`var style = '<style>.buorg {background: #FDF2AB no-repeat 14px center url(' + burl + 'img/small/' + bb.n + '.png);}</style>';`
