### ISSUE TITLE
more instances of file:// found

### ISSUE THREAD

**Issue by marathia** [browser-update/browser-update#333]
In addition to #331: I found more places in update.show.min.js that prevent the script from working properly when running it locally:

`var style = '<style>.buorg {background: #FDF2AB no-repeat 14px center url(' + burl + 'img/small/' + bb.n + '.png);}</style>';`

`t=busprintf(t,bb.t,' id="buorgul" href="'+this.op.url+'"'+tar);`

**Comment by josselex** [comment]
fixed in 6902351
