### ISSUE TITLE
Feature idea: Compatibility mode

### ISSUE THREAD

**Issue by peter-the-oak** [browser-update/browser-update#334]
The customers in my project do have an IE 11 but for incomprehensible reasons they have set it to compatibility mode 8..10. So if browser-update notifies "Your IE11 is too old", it is not quiet true. 

There seem to be no placeholder for the compatibility mode. 

Would it be valuable to be able to notify about the compatibility mode?

**Comment by josselex** [comment]
Usually this should already be detected correctly as IE 11. I will check if there is something wrong.

**Comment by josselex** [comment]
Sorry. I misunderstood the idea.
Yes. It would be cood to add onther text that says "Please turn off Compytibility mode for this website".
Did I get the idea correctly?
I think about implementing this.

**Comment by josselex** [comment]
Isn't it enough to insert
 ` <meta http-equiv="X-UA-Compatible" content="IE=edge"/> `
into your site that it is not rendered in compatibility mode?

**Comment by josselex** [comment]
To have your site rendered in compatibilty mode you should add the mentioned meta tag.
