### ISSUE TITLE
New Feature - Browser by Feature

### ISSUE THREAD

**Issue by stunaz** [browser-update/browser-update#337]
Hi, came accross this lib.
Really Nice.

Instead of declaring which version of the browser we want, would it be possible to declare what feature we want for the browser, and the `browser-update` detects which browser are available to for it them.

i.e. , lets say I want to make sure that browser client have `flexbox`. `browser-update` will then detect if the browser client support `flexbox`, if not it will propose browse with minimal versions that support it

**Comment by josselex** [comment]
Fortunately, this idea is already on my todo list. I will implement it in the next weeks.

**Comment by josselex** [comment]
I think about combining it with modernizr in an example.
