### ISSUE TITLE
some translation inconsistencies

### ISSUE THREAD

**Issue by marathia** [browser-update/browser-update#341]
When setting the language to `ca`, `fa`, `ga`, `gl`, `he`, `hi`,` lv`, `sl`, `sq`, `sr` or `th` (like `l: "ca",`), a different layout is used (no buttons, but a text link and a close icon in the upper left corner).

`hr`, `ro` and `nb` show the message in English.

Portugese has a typo: `{nome_nav}` instead of `{brow_name}`.

The output of `l: "sr",` is recognized by Google Translate as Bosnian, instead of Servian.

**Comment by josselex** [comment]
These languages were not translated yet for the new layout. When they are translated, they will be shown with the new layout.
The Portugese link will be fixed.

**Comment by josselex** [comment]
I should somehow mark the messages as needing translation

**Comment by josselex** [comment]
should "nb" fallback to "no"?

**Comment by marathia** [comment]
Reopening this issue, because there are still issues:

`vi` shows no buttons
`ga`, `nb` and `rm` show the English text
`gl`, `lv`, `sr` and `sl` still show the old layout
