### ISSUE TITLE
Google bots using "Chrome/27.0" triggering warning

### ISSUE THREAD

**Issue by pdbreen** [browser-update/browser-update#342]
This is more of a question than an issue, but I couldn't find any open/closed issues or how others may be handling it.  I've recently noticed that various google index & rendering services (page speed, webmaster tools fetch & render) use a bot with Chrome/27 in the agent string.  From http://stackoverflow.com/questions/16403295/what-is-the-name-of-the-google-pagespeed-user-agent

```
for MOBILE:

Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko; Google Page Speed Insights) Chrome/27.0.1453 Mobile Safari/537.36

FOR DESKTOP

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko; Google Page Speed Insights) Chrome/27.0.1453 Safari/537.36
```

The renderings that result end up with the warning that Chrome 27 is an old browser and should be updated.  Have others done anything to prevent this?  

My app happens to already include a user agent parser so I'm going to see if I can just conditionally include the browser detect for non-bots, but it seems maybe this could be something done from within the service itself.

**Comment by josselex** [comment]
I am now ignoring the page speed insights. Do you know the user agent of the other services you mentioned?

**Comment by pdbreen** [comment]
I use the JayBizzle/Crawler-Detect package for bot detection.  You could cherry-pick from the list of patterns it makes use of:  https://github.com/JayBizzle/Crawler-Detect/blob/master/src/Fixtures/Crawlers.php

I believe "Google Search Console" is the what webmaster tools crawls with.

Thanks!

**Comment by josselex** [comment]
awesome. thank you. I will partly include this in my block-list.

**Comment by josselex** [comment]
I incorporated the most important bots from the list in 6bc9230
I tried to use general blocking terms like bot, crawl, ..
