### ISSUE TITLE
detect the browser in iOS

### ISSUE THREAD

**Issue by marathia** [browser-update/browser-update#343]
Isn't it possible to detect the browser in iOS? Currently Safari, Chrome and Opera show 'Your web browser (other browser) is out of date.'

Tested in iOS 9.3.5, but changing the user agent to any version of iOS in a desktop browser shows the same.

**Comment by josselex** [comment]
I'm working on it. 
The problem was that on iOS you need to update the OS to update the Browser.
I did not know if there are updates available because this depends on the particular iPhone/iPad model. I now figured out a way to detect it at least for iPhones and the iPad Pro.

**Comment by marathia** [comment]
I understand now. Your work is much appreciated!

**Comment by josselex** [comment]
I turned on the notification for news iOS devices today. I will test it for a few days.

**Comment by marathia** [comment]
The message looks good for iOS>1 with `test: true` and fiddling with the user agent in Firefox using User Agent Switcher!

Only iOS1 results in *iOSNaN* but I think anyone will have a problem with that :)
