### ISSUE TITLE
full URL for the update button in update.min.js

### ISSUE THREAD

**Issue by marathia** [browser-update/browser-update#344]
In addition to #331 and #333: could you please change 

`else this.op.url = op.url || "//browser-update.org/update-browser.html#" + jsv + ":" + pager;`
to
`else this.op.url = op.url || "http://browser-update.org/update-browser.html#" + jsv + ":" + pager;`

in update.show.min.js? This way, the update button will also work when running it locally.

**Comment by josselex** [comment]
Your code seems rather old. This should have been already fixed. Where did you see the code?

**Comment by marathia** [comment]
It was on http://browser-update.org/update.min.js, line 3, starting at character 4207. Don't know if it was my mistake, but the code is now
`else this.op.url=op.url||"//browser-update.org/update-browser.html#"+jsv+":"+pageurl;`

It makes the link of the update button fail when running the page locally (`file:///update-browser.html#24:x`).

**Comment by josselex** [comment]
Try a reload!

**Comment by marathia** [comment]
I did, but that doesn't change it…

**Comment by josselex** [comment]
finally it should work now

**Comment by marathia** [comment]
👍
