### ISSUE TITLE
Vivaldi 1.10 detected as Vivaldi 1.1

### ISSUE THREAD

**Issue by bbluemel** [browser-update/browser-update#348]
Vivaldi 1.10  was just released: https://vivaldi.com/blog/snapshots/docked-developer-tools-vivaldi-browser-snapshot-1-10-829-3/

And is being detected as 1.1 as per the following screenshot. 

http://i.imgur.com/WoJbocC.png

:)

**Comment by josselex** [comment]
Thanks for reporting! This is fixed now in https://github.com/browser-update/browser-update/commit/40ee8d8e83513f21efe58a5075d45bed718367d8 and https://github.com/browser-update/browser-update/commit/674157d71c3b82a880d277474606d1da072696c0
