### ISSUE TITLE
Is it possible to deploy this through the Google Tag Manager?

### ISSUE THREAD

**Issue by nakitadog** [browser-update/browser-update#349]
Is it possible to deploy this through the Google Tag Manager?

**Comment by josselex** [comment]
It should work if you choose custom html. 
Like here:
http://help.qualaroo.com/hc/en-us/articles/201405386-Installing-the-JavaScript-using-Google-Tag-Manager

Can you report if it worked for you?

**Comment by nakitadog** [comment]
That's how I tried to implement it but it did not work. After receiving some help from the Google GTM forum, I was able to get it to work. 

I had to do the following:

Step 1: Setup a JavaScript Variable called $buoop.

Step 2: Add the following modified code to a Custom HTML tag:

```javascript
<script>
  (function() {
    window['$buoop'] = {vs:{i:10,f:30,o:30,s:6,c:40},api:4};
    var e = document.createElement('script');
    e.src = '//browser-update.org/update.min.js';
    document.body.appendChild(e);
  })();
</script>
```

Step 3: Trigger the code using the built-in All pages tag. 

That worked for me. 

Do you foresee any issues with that approach?

**Comment by josselex** [comment]
Hi!
I think this should work. you can simplify this to

```javascript
<script>
  (function() {
    window.$buoop = {vs:{i:10,f:30,o:30,s:6,c:40},api:4};
    var e = document.createElement('script');
    e.src = '//browser-update.org/update.min.js';
    document.body.appendChild(e);
  })();
</script>
```

And i think you do not need to "Setup a JavaScript Variable called $buoop."

Can you verify that it works?

**Comment by nakitadog** [comment]
Yes, that works. 

But I am only testing it based on your test code #test-bu 

Do you know if this would actually work in old browsers?

Here's my test page:
http://www.lizardlogic.com/gtm/code-in-gtm.html#test-bu

**Comment by josselex** [comment]
I checked it with a cross browser testing tool. It works.

2017-05-09 14:02 GMT+02:00 nakitadog <notifications@github.com>:

**Comment by nakitadog** [comment]
Thank you.

**Comment by josselex** [comment]
Somehow it does work for Safari 6.2 but not for Safari 6. I will check this
tomorrow.

2017-05-09 16:33 GMT+02:00 Thomas Hümmer <jossele@gmx.de>:

**Comment by josselex** [comment]
I think the reason for Safari is the same like in bug #357
