### ISSUE TITLE
suggestion: "use strict;"

### ISSUE THREAD

**Issue by Jens-G** [browser-update/browser-update#354]
I'd suggest to add "use strict;" on top of all JS files and check whether everything works as expected. This is not really a bug or problem, but a suggestion (and also state of the art).

**Comment by dx76** [comment]
I think that is A very good suggestion thank you very much respectfully BrentD

**Comment by josselex** [comment]
Good idea to prevent and find bugs. I will implement and test it in the
next weeks.

2017-06-06 7:35 GMT+02:00 dx76 <notifications@github.com>:

**Comment by josselex** [comment]
fixed in e049ee73dfc2be9e5a21e2a1417cba2e6bf82b2f
