### ISSUE TITLE
Cant select safari 11 as minimum version

### ISSUE THREAD

**Issue by KoIIIeY** [browser-update/browser-update#358]
Can you update script for checking safari that lower 11 ?

**Comment by mscuthbert** [comment]
Related: With the release of Safari 11 -- after 10.1 and 10.0 -- is there any chance that the default settings will warn Safari <= 9 now?  This would leave only IE as a browser that doesn't support ES6 in the default warnings.

**Comment by josselex** [comment]
Ok! Let's make this the default choice. 
Safari 11 checking will come tomorrow. I have some issues updating it.

**Comment by josselex** [comment]
Finally! It should work now! (Make sure to clear your cash if it does not when you're testing)

Default Safari Version to notify is now 9
