### ISSUE TITLE
javascript for browser-update breaks if the web page app breaks

### ISSUE THREAD

**Issue by phun-ky** [browser-update/browser-update#359]
We have an app that only supports IE 10 and above. We have implemented the browser-update script, but when viewing the app in < IE9, the app breaks, and the browser-update code will not load.. Is there a way to fix this?

**Comment by josselex** [comment]
If you add the code before your custom code I think that should not happen.

**Comment by josselex** [comment]
Adding the browser-update script before your code should do the trick.
Browser-update is then loaded when the onload event is fired and this should always fire, regardless if there was an error.
