### ISSUE TITLE
Using 'negative numbers' to specify how many versions behind the current version to notify not working correctly. 

### ISSUE THREAD

**Issue by jlsorak** [browser-update/browser-update#360]
The comment in the options on [this page](http://browser-update.org/customize.html) says, you can use "Negative numbers [to] specify how much versions behind current version to notify."

However, this doesn't appear to be working consistently - I've been using [browserstack](www.browserstack.com) to test this and I have set -1 for all browsers. So technically it should show the message on any browser that is 1 version behind the current version. 

In reality, here are the results I have found: 
Current Firefox version : 55
Doesn't notify on version: 54
Shows notification on version: 53

Current Chrome version: 61
Doesn't notify on version: 60
Doesn't notify on version: 59
Shows notification on version: 58

Current Safari version: 10.1
Shows notification on version: 9.1

**Comment by josselex** [comment]
As you already found out the issue is that the current versions where not updated in the last weeks. I usually do this once a month.
Give me some time to upload it. It'll be done today.

**Comment by jlsorak** [comment]
Thanks for the quick response 👍

**Comment by josselex** [comment]
Sorry, the version number fix is not yet online. I have some trouble updating it. I hope that it works tomorrow.

**Comment by jlsorak** [comment]
Using 'negative numbers' still isn't working as it should. I thought updating the the browsers.json file in https://github.com/browser-update/browser-update/pull/361 was going to fix this? Is there something else causing an issue?

**Comment by josselex** [comment]
I know! Sorry.
I fixed the stuff also in the other places where it is needed.
However, I'm stuggling with clearing our sever's cache.
If you are using the npm version it should work as expected right now. 
I'm hoping to get it working today.

**Comment by jlsorak** [comment]
I'm not using the NPM version unfortunately. Good luck with it 👍

**Comment by josselex** [comment]
Finally! It should work now! (Make sure to clear your cash if it does not when you're testing)

**Comment by jlsorak** [comment]
Tested on FF, IE, Chrome and Safari, all LGTM 👍  Thanks for this!
