### ISSUE TITLE
Firefox 52 doesn't display popup

### ISSUE THREAD

**Issue by jlsorak** [browser-update/browser-update#362]
Firefox 52 doesn't display a popup, I've tested this with the script on my site and also on https://browser-update.org/ using Browserstack. Tested on windows 10, 8 and 7.

**Comment by josselex** [comment]
Firefox is a long term supported Version of firefox and still supported and the last version for windows XP.
It will be notified starting march 2018.
Long term versions are often used in companies who are reluctant to update every 6 weeks.
I am about to add an option to explicitly override the behaviour and notify even supported versions. Would that be helpful for you or are you ok with it not being notified till march?

**Comment by jlsorak** [comment]
I wasn't aware of that, thank you for the explanation. Personally it would be preferential to have an option to override the behaviour, as my use case requires me to notify users with browsers that our company no longer supports, and as Firefox 52 is not one of those, we would still want to notify users of that browser. 

If that's possible that would be awesome!

**Comment by Chabnar** [comment]
Whats the status on this? It still doesn't work on older versions of Firefox.

**Comment by josselex** [comment]
Hi. I'll try to post a fix during the next week.

Am Fr., 20. Juli 2018 um 17:26 Uhr schrieb Cassandra Torske <
notifications@github.com>:

**Comment by josselex** [comment]
You can now add the option
`notify_esr: true`
to also notify "Extended support release" (ESR) versions of firefox.
These versions are currently 52 and 60
