### ISSUE TITLE
Notification's invisible in iOS 9.3.5 and 10.3.3

### ISSUE THREAD

**Issue by branditodesigns** [browser-update/browser-update#363]
The notification isn't appearing in **Safari or Chrome for 9.3.5 and 10.3.3** using #test-bu & the test:true option.
Any ideas?
The notification pushes the html element for the available space and has the golden border-bottom but the actual notification body is missing.

**Comment by branditodesigns** [comment]
This seems to be caused by the margin being added to the HTML element and not the body element, this is a known problem for iOS I thought.

**Comment by josselex** [comment]
Seems to be a particular problem with your website, because it works on the sites I tested with. Could you send the link to your site?

**Comment by branditodesigns** [comment]
Haven't got it live yet, will attempt to figure out what's wrong myself and report back.

**Comment by josselex** [comment]
No information. Closing
