### ISSUE TITLE
auto margin top needs auto padding bottom

### ISSUE THREAD

**Issue by branditodesigns** [browser-update/browser-update#364]
While the notification message is showing & pushed down with a margin-top on the HTML element our websites footer is missing a chunk the same size as the HTML margin top.
Adding the margin top value to the padding bottom value fixes it although stuff like this I thought would have been tested?

**Comment by branditodesigns** [comment]
Fixed it on my end using this as the onshow callback function:
function addPaddingBottom() {
    if(parseInt($('html').css('margin-top')) > 0)
        $('html').css('padding-bottom', $('html').css('margin-top'));
}

**Comment by branditodesigns** [comment]
Forgot about when you dismiss/close the notification, this is now my onshow and onclose callback function:
```
function handlePadding() {
        $('html').css('padding-bottom', $('html').css('margin-top'));
}
```

**Comment by josselex** [comment]
You can now stop pushing down the page by supplying the option
`shift_down_page:false`
http://browser-update.org/customize.html

**Comment by jdolearydl** [comment]
FYI, It is now called `shift_page_down` not shift_down_page
