### ISSUE TITLE
Latest version of Opera for Android classified as old

### ISSUE THREAD

**Issue by nibarius** [browser-update/browser-update#366]
The "Opera for Android" browser is the mobile version of the Opera browser for Android phones. The version number, browser and platform are all detected correctly. However the latest release of Opera for Android is 43.0 which was released on the 27th of September according to https://play.google.com/store/apps/details?id=com.opera.browser

But browser-update assumes that 48 is the latest version since the latest version of the desktop browser is 48 so it incorrectly flags the Android version of Opera as outdated.

Example user agent for the latest version of Opera for Android:
`Mozilla/5.0 (Linux; Android 6.0.1; SM-A320FL Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.116 Mobile Safari/537.36 OPR/43.0.2246.121183`

**Comment by josselex** [comment]
Indeed!
I'm about to fix it.
Thank you for reporting!

2017-11-06 17:41 GMT+01:00 Niklas Barsk <notifications@github.com>:

**Comment by nibarius** [comment]
Awesome, I'm no longer getting warnings on the latest version. Thanks!
