### ISSUE TITLE
vsunsecure is not defined

### ISSUE THREAD

**Issue by sshmyg** [browser-update/browser-update#368]
Hi, got error, here http://browser-update.org/update.min.js
`Uncaught ReferenceError: vsunsecure is not defined`

Incorrect variable name `var vsinsecure = {};` - can you fix it, please?

**Comment by ants88** [comment]
I've changed unsecure to insecure in configuration object, like http://browser-update.org/

**Comment by josselex** [comment]
I fixed it. Thank you for reporting.
