### ISSUE TITLE
vsunsecure is not defined

### ISSUE THREAD

**Issue by AnnAngela** [browser-update/browser-update#369]
When I inserted the [update.min.js](https://browser-update.org/update.min.js) in my web page, I got an error:
```
Uncaught ReferenceError: vsunsecure is not defined
    at $buo (update.min.js:formatted:196)
    at update.min.js:formatted:239
```
I found issue #368 where someone said that the error had been fixed, and I really found the `vsinsecure` in the Line 19 of [update.js](https://browser-update.org/update.js), and sth. in the Line 31: 
```
vs[b]=vsmin[b];if((op.insecure||op.unsecure)&&vsinsecure[b]&&vs[b]<vsinsecure[b])
```
But, in the Line 3 of update.min.js, there are still `vsunsecure`s: 
```
... if(op.unsecure&&vsunsecure[b]&&vs[b]<vsunsecure[b])vs[b]=vsunsecure[b];} ...
```
Maybe you guys should repack your code.

**Comment by josselex** [comment]
I guess you still have the old cached version... Try shift+reload in your
browser. Here I get the correct file.

2017-11-18 5:14 GMT+01:00 AnnAngela <notifications@github.com>:

**Comment by AnnAngela** [comment]
Good, the incorrectly cache had been clean.
