### ISSUE TITLE
Issue with Internet Explorer

### ISSUE THREAD

**Issue by acasari** [browser-update/browser-update#370]
Hi, 
I would like to warn users that use any sort of IE browser, that the preferred browser is Chrome/Firefox. For that I am using:

```
<script> 
var $buoop = {notify:{i:14},insecure:true,api:5, reminder: 24, text:"Su navegador {brow_name} no está soportado para esta configuracion de JIRA. Se recomienda usar Chrome o Firefox.... <a{ignore_but}>ignorar</a>"}; 
function $buo_f(){ 
 var e = document.createElement("script"); 
 e.src = "//browser-update.org/update.min.js"; 
 document.body.appendChild(e);
};
try {document.addEventListener("DOMContentLoaded", $buo_f,false)}
catch(e){window.attachEvent("onload", $buo_f)}
</script>
```

However that doesn't show any popup. If I change reminder:0 it work, but the popup is always shown, even if you click on Ignore.

Thanks in advance,

**Comment by josselex** [comment]
I fixed the problem with the bar reappearing even after pressing the "ignore" button.
Commit 4d803feda03e8a9967e4dbbb8b56a53f47acb3b5

Warning the users on internet explorer <=14 shoud however work. Check that you clear your cookies before testing.
