### ISSUE TITLE
Add custom browser versions to wordpress plugin

### ISSUE THREAD

**Issue by joEnder** [browser-update/browser-update#372]
I’m using the wordpress plugin in my company and I stumbled across a problem.

In the wordpress BE I selected that the “old browser” box should appear on safari on version 8.
On the iPad Air 2 the text doesn’t appear. When I debugged through the code I noticed that the iPad says that his user agent has the version 8.1, which is greater than 8 so everything is correct.

So I searched for a Filter/Action to add a custom version (like 8.9) to the BE. Sadly I didn’t find any suitable ones.

So would it be possible to add such a Filter/Action to the code? If not I’m also open to other solutions.

**Comment by josselex** [comment]
I saw that you already wrote to the creator of the Wordpress plugin here:
https://wordpress.org/support/topic/add-custom-browser-versions/

Unfortunately, if I understand your problem correctly, I have to point you back to him.
On our site you can simply notifiy safari versions <8.9, but i think in the wordpress plugin the option to enter a custom number is missing. Am I right?

As a temporary solution you can simply use our Javascript code without the wordpress plugin.

**Comment by joEnder** [comment]
Ok, then I try it over there again and thanks for the tip with the solution.
