### ISSUE TITLE
Message fades out but is not removed when clicking Ignore

### ISSUE THREAD

**Issue by 29thfloor** [browser-update/browser-update#374]
I'm using this in Chrome 63 (in test mode) and when I click Ignore, the message slowly fades out but the (now transparent) container stays on the screen, blocking everything behind it.

**Comment by josselex** [comment]
This should be fixed now. Can you check if it works now?

**Comment by 29thfloor** [comment]
Sorry for the delay. Yes it seems to be working now. Thanks!
