### ISSUE TITLE
Firefox 58.0.2 is notified as outdated

### ISSUE THREAD

**Issue by chogberg** [browser-update/browser-update#377]
I get a notification that I need to update my browser when visiting a site using this browser detection script. My version is Firefox 5.8.0.2 running on Android 6.0.1

**Comment by josselex** [comment]
Hi!
On which site did you see the notification?


2018-02-18 15:40 GMT+02:00 chogberg <notifications@github.com>:

**Comment by josselex** [comment]
Cannot reproduce. Must be a problem with a specific site using the script. But I have no information on this.
