### ISSUE TITLE
Consider allowing downloading translation files from Crowdin.

### ISSUE THREAD

**Issue by teo-tsirpanis** [browser-update/browser-update#380]
This will allow translation from tools like Poedit.

**Comment by josselex** [comment]
Hi Teo!
This is already possible . You have to click on "..." next to the translation file and choose "download".

**Comment by teo-tsirpanis** [comment]
No, it's not possible.

![Poedit displays an error](https://user-images.githubusercontent.com/12659251/38936420-6ee2d7da-4329-11e8-9957-c2e65cb95807.png)

![Where is the download button?](https://user-images.githubusercontent.com/12659251/38936548-b2104434-4329-11e8-836e-361f95a68da5.png)

You see the button exists, because you are a project manager. You can see [here](https://support.crowdin.com/advanced-project-setup/) how to enable downloads.

**Comment by josselex** [comment]
Sorry!
Now I understand.
I enabled it now.

2018-04-18 16:00 GMT+02:00 Theodore Tsirpanis <notifications@github.com>:
