### ISSUE TITLE
Browser version detection issue

### ISSUE THREAD

**Issue by dziksu** [browser-update/browser-update#382]
Hi,

when I use config like:

`var $buoop = {
notify:{i: 11, f: 54, o: 45, s: 10, c: 58}, 
insecure:true, 
unsupported: true,
api:5
}; 
`

then for chrome **65.0.03325.181 (64-bit)**  I received information:
`Your web browser (Chrome 65) is out of date.`

**Comment by josselex** [comment]
Hi!
I somehow cannot reproduce this with my chrome 65. Can you tell me what you see on this page:
http://browser-update.org/test/bar.html

Then I an try to debug this.

**Comment by josselex** [comment]
Hi
You have " unsupported:true " in your configuration. Chrome 65 was superseded by chrome 66 6 days ago.
This is why it gets notified.

**Comment by josselex** [comment]
Usually we will wait for about 2 weeks till we will notify unsupported versions.
