### ISSUE TITLE
Distinguish IE and Edge

### ISSUE THREAD

**Issue by sco2tbold** [browser-update/browser-update#383]
In your demo script IE and Edge cannot be configured separately. It's all merged in the e parameter, right? 

`{notify:{e:-6,f:-4,o:-4,s:-2,c:-4},insecure:true,api:5}; `

Is there a way to control the IE version separetely from Edge? 

`{notify:{i: -3, e:-6,f:-4,o:-4,s:-2,c:-4},insecure:true,api:5}; `

(btw: Big thanks for the great product!)

**Comment by josselex** [comment]
This should actually work. However to target the old internet explorer
version specify it with a positive number:

e.g.

i:9

or whatever

Best,
Thomas

2018-04-23 12:29 GMT+02:00 Scott Bold <notifications@github.com>:

**Comment by sco2tbold** [comment]
Thanks. Can I force to notify all IEs with something like: 
{notify:{i:0,e:-6,f:-4,o:-4,s:-2,c:-4},insecure:true,api:5};

**Comment by josselex** [comment]
You can use i:11

Or just use e:-4 and omit the i

2018-04-24 10:58 GMT+02:00 Scott Bold <notifications@github.com>:

**Comment by josselex** [comment]
This works now.
See
http://browser-update.org/blog/18_notify_outdated_ie_and_edge_separately/
