### ISSUE TITLE
exclude sparrow browser from update notification

### ISSUE THREAD

**Issue by jdtsillas** [browser-update/browser-update#386]
Sparrow is a browser created by Viasat. The user-agent string identifies it as:

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.16817 Safari/537.36 Sparrow/0.1

As of now the version 0.1 is not incremented between builds. Sparrow is based on Chrome  but is typically a few release behind. Our users have reported the browser-update banner.

**Comment by josselex** [comment]
I included it in the whiteliste. Will be online on monday.
