### ISSUE TITLE
BUG: Notification close after click, even if noclose is set up

### ISSUE THREAD

**Issue by tomasztomys** [browser-update/browser-update#387]
BUG: Notification close after click UPDATE, even if noclose is set up

**Comment by josselex** [comment]
no_close only specifies that there should be no button to close the
notification WITHOUT updating. If you update, the notification should of
course go away.

What case do you have in mind?

2018-04-30 16:06 GMT+02:00 Tomasz Tomys <notifications@github.com>:

**Comment by josselex** [comment]
I'm closing this issue. If you have more suggestions, please fell free to reopen.

**Comment by tomasztomys** [comment]
@josselex it's a problem if your user click UPDATE, but then he will not do it and back to your site without notification about not supported/not updated browser

**Comment by josselex** [comment]
But then he has already read it, right? Isn't this enough? I made it
disappear to make it as simple as possible for the user.

2018-05-04 14:07 GMT+02:00 Tomasz Tomys <notifications@github.com>:
