### ISSUE TITLE
feature_request(options): links into notification area

### ISSUE THREAD

**Issue by Kristinita** [browser-update/browser-update#390]
### 1. Summary

It would be nice, if custom links will work into notification area.

### 2. Example

+ my `SashaBrowserUpdate.html` file:

```html
<script>
var lifewire = "Lifewire";
var quora1 = "Quora";
var alternative = "Alternative.to";
var slant = "Slant";
var quora2 = "Quora";
var $buoop = {notify:{i:4147},
api: 5,
reminder: 0,
text: "I'm sorry, {brow_name} and any another IE versions not supported on this site. Page can be displayed very incorrect. Arguments, why all Internet Explorer version is a bad choice — " + lifewire.link("https://www.lifewire.com/why-do-people-hate-internet-explorer-3485786") + quora1.link("https://www.quora.com/Is-Internet-Explorer-really-as-bad-as-everyone-tries-to-make-out") + ". Recommendations at the choice of the browser for Windows:" + alternative.link("https://alternativeto.net/software/internet-explorer/?platform=windows") + slant.link("https://www.slant.co/topics/11157/~web-browsers-for-windows") + quora2.link("https://www.quora.com/Which-is-the-best-browser-for-windows-10") + "."};

function $buo_f(){
 var e = document.createElement("script");
 e.src = "//browser-update.org/update.min.js";
 document.body.appendChild(e);
}

try {document.addEventListener("DOMContentLoaded", $buo_f,false);}
catch(e){window.attachEvent("onload", $buo_f);}
</script>
```

+ Notification in Internet Explorer:

![Notification](https://i.imgur.com/07FcahM.png)

### 3. Steps to reproduce

For Internet Explorer:

    user left-click to `Lifewire`

### 4. Expected behavior

**<https://www.lifewire.com/why-do-people-hate-internet-explorer-3485786>** link open.

### 5. Actual behavior

**<https://browser-update.org/update-browser.html#3.0.6>** link open.

### 6. Not helped

I try add [**properties**](https://browser-update.org/customize.html):

    url: null,

**or**

    url: false,

No effect.

Thanks.

**Comment by Kristinita** [comment]
@josselex,

**Status: :book: I need more docs**

### 1. Summary

[**Changelog**](https://github.com/browser-update/browser-update/commit/18593c4502e0f41738cdd6b839fc2c8d522c3327#diff-e8800259c4985f4a73b0936128034c53R8):

> do not make the whole bar clickable (if update button is present). this is also to allow custom text with links

But browser-update bar still clickable for me.

### 2. Configuration

```html
<meta charset="utf-8">
<script>
var lifewire = "Lifewire";
var quora1 = "Quora";
var alternative = "Alternative.to";
var slant = "Slant";
var quora2 = "Quora";
var $buoop = {notify:{i:4147},
api: 5,
reminder: 0,
text: "I'm sorry, {brow_name} and any another IE versions not supported on this site. Page can be displayed very incorrect. Arguments, why all Internet Explorer version is a bad choice — " + lifewire.link("https://www.lifewire.com/why-do-people-hate-internet-explorer-3485786") + ", " + quora1.link("https://www.quora.com/Is-Internet-Explorer-really-as-bad-as-everyone-tries-to-make-out") + ". Recommendations at the choice of the browser for Windows: " + alternative.link("https://alternativeto.net/software/internet-explorer/?platform=windows") + ", " + slant.link("https://www.slant.co/topics/11157/~web-browsers-for-windows") + ", " + quora2.link("https://www.quora.com/Which-is-the-best-browser-for-windows-10") + "."};

function $buo_f(){
 var e = document.createElement("script");
 e.src = "//browser-update.org/update.min.js";
 document.body.appendChild(e);
}

try {document.addEventListener("DOMContentLoaded", $buo_f,false);}
catch(e){window.attachEvent("onload", $buo_f);}
</script>

```

### 3. Data

Steps to reproduce and expected behavior as in [**first post**](https://github.com/browser-update/browser-update/issues/390#issue-319188206).

### 4. Actual behavior

+ **<https://www.lifewire.com/why-do-people-hate-internet-explorer-3485786>** open in current tab
+ **<https://browser-update.org/update-browser.html#3.0.8>** open in external tab

Thanks.

**Comment by josselex** [comment]
Hi!
Now with 3.1.0 the bar is not clickable if a custom text is supplied. So it should work for you.
