### ISSUE TITLE
privacy concerns

### ISSUE THREAD

**Issue by AndreBaumeier** [browser-update/browser-update#392]
Hello,

from your privacy statement it is not clear what type of user information you are actively tracking and storing for further use. Same goes for Cookies being set / used for identifying wether a user dismissed the notification. In order to comply with gdpr these information are crucial and should be provided.

Can you help out here?

**Comment by josselex** [comment]
Hi. I'm currently rewriting the site. There it should get clearer:
"The script is not tracking users in any way and does not collect any personal information."

Is it clear from this?

**Comment by josselex** [comment]
The cookie can not identify users. It just sets if the notification was already shown.

**Comment by josselex** [comment]
The information is now present on the site
https://browser-update.org
