### ISSUE TITLE
Update notifications on wrong browser versions

### ISSUE THREAD

**Issue by johnsherwindublin** [browser-update/browser-update#393]
Hi, I had configured browser-update to only trigger notification for browsers older than specific versions. 

`var $buoop = {required:{i:9,e:12,f:27,o:20,s:7.1,c:33}`

This seemed to be working fine until recently, I think maybe after the April updates you made? I have tried to re-configure but the problem is that later versions than I have specified are showing notification.

In the example below want to show notification for Firefox 27 and earlier, but the notification appears on all versions of Firefox up to and including 55 and all versions of Chrome up to and including 61.

Is there something about the configuration that is incorrect so it is defaulting to a certain number of versions older than latest instead of my specific browser versions?

`<script>
var $buoop = {required:{i:9,e:12,f:27,o:20,s:7.1,c:33},insecure:true,api:2018.05 };
function $buo_f(){
var e = document.createElement("script");
e.src = "//browser-update.org/update.min.js";
document.body.appendChild(e);
};
try {document.addEventListener("DOMContentLoaded", $buo_f,false)}
catch(e){window.attachEvent("onload", $buo_f)}
</script>`

Thanks!

**Comment by josselex** [comment]
Hi!
insecure: true in your configuration means that all browsers with severe security issues get notified.
See 
http://browser-update.org/blog/18_notifying_insecure_outdated_browsers/
https://github.com/browser-update/browser-update/wiki/Details-on-configuration#notifying-insecure-browsers

**Comment by johnsherwindublin** [comment]
Hi josselex, thank you so much for coming back to me quickly with a solution. I had overlooked the security notification configuration. For me I am using browser update to warn people that the website will not display properly for certain versions rather than security. It would be great to display two different notifications for these purposes. Thanks for all your work on a great tool.

**Comment by johnsherwindublin** [comment]
Wow, that's great :)

**Comment by josselex** [comment]
> Are you using a source to determine what browser versions have serious security risks?

I'm using the release blog and cve.

The sources are found in 
https://github.com/browser-update/browser-update/blob/master/browsers.json
under
"security bulletins:"
"cve:"
"blog:"
