### ISSUE TITLE
Projects like your's just don't get it

### ISSUE THREAD

**Issue by Claverhouse** [browser-update/browser-update#394]
People like me don't refuse to update browsers because of stubbornness or lack of awareness:  it's because all modern browsers went over to the minimalist, clean, bare, Fat Slab, material design, Flat Style, Chromified empty-minded crap that is just fucking ugly.

If I have to be on the web for extended periods of time, why make that experience miserable with minimalism ?  Circa 2012 a Firefox with plenty of superb extensions was a thing of beauty.  Now, it and the rest like Brave or Vivaldi are just tin cans.

I've installed plenty of browsers ( currently on Mint ) all up-to-date, but I use the good-looking ones of the past.  And even this Fx 45 has to have Classic Theme Restorer to undo the damage Mozilla did to copy Google.

**Comment by josselex** [comment]
I'm sorry that you don't like the look of the newer browsers.

However, some sites only work in newer browsers and old browser versions
are insecure. That is all we are informing you about.

We now habe the option to disable to show the notification permanently. I
hope this solves your problem.

2018-05-10 6:02 GMT+02:00 Claverhouse <notifications@github.com>:
