### ISSUE TITLE
Waterfox is up to date

### ISSUE THREAD

**Issue by ShonkaiDJ** [browser-update/browser-update#396]
Not sure if you get the right info from the brand new real fork from Firefox, Waterfox. But it's kind of annoying if you guys will keep interfering while nothing is wrong.

I will add this to the Waterfox project too (also here on Github) but just so you know: Waterfox is not an out of date Firefox. Just a different one.

**Comment by grahamperrin** [comment]
Thanks, cross reference: 

- https://github.com/MrAlex94/Waterfox/issues/577

Some context: 

- [User-Agent: Waterfox · Issue #178 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/178)

– tl;dr AFAIR too many unexpected issues arose from use of a Waterfox-oriented UA; and then those issues ended when usage changed (note to self: if there's not already a note of the PR/commit in 178, someone ought to add it).

**Comment by josselex** [comment]
Waterfox is now being whitelisted (for now).

**Comment by grahamperrin** [comment]
https://github.com/MrAlex94/Waterfox/issues/178#issuecomment-407028195 noted. 

Thanks again for the period of whitelisting, I guess that it has ended. For reference only (Waterfox 56.2.2 still identifying itself as outdated Firefox 56): 

![2018-08-09 07 32 34 france-ioi principe de l entrainement - waterfox](https://user-images.githubusercontent.com/192271/43882332-3e4727b2-9ba7-11e8-8a70-d48a86034590.png)
