### ISSUE TITLE
Uncaught ReferenceError in v3.1.7

### ISSUE THREAD

**Issue by rejas** [browser-update/browser-update#398]
Hi, I just updated from v3.1.6 to v3.1.7 using the npm package:

import BrowserUpdate    from 'browser-update/update.npm.js';

With v3.1.6 the update dialog appears when testing it, but with the new version in the console this appears (and nothing else happens):

Uncaught ReferenceError: jsv is not defined
    at $buo (update.npm.js:169)

**Comment by josselex** [comment]
This should be fixed now in 3.1.8

2018-05-23 18:44 GMT+02:00 Veeck <notifications@github.com>:

**Comment by rejas** [comment]
It is indeed, thanks for the quick fix!
