### ISSUE TITLE
Supported browser (IE9) getting grouped with unsupported browsers

### ISSUE THREAD

**Issue by korynorthrop** [browser-update/browser-update#400]
Thanks for making this awesome library. I am implementing this on my staging server right now and the goal is to redirect IE8 and lower to a page that explains that their browser is insecure and provide them information/resources to update. Yes, maybe it's bad practice because it prevents them from viewing our site, but it's a decision we decided to make anyway.

The issue I'm having is that IE9 is getting flagged as unsupported despite setting IE8 as cutoff version. It's possible I'm just not using the `required` key properly. Here is my code:

```
<?php 
   // Create DOM element that determines whether visitor is redirected to upgrade browser page
   $insecure_browser_link = esc_url(get_permalink(427567)); // page_id of page to redirect to
   $is_incompatibility_page = (is_page(427567)) ? true : 'nope'; // don't redirect if on that page
?>
<div id="incompatibility-container" class="hidden" data-where="<?php echo $insecure_browser_link; ?>" data-compatible="<?php echo $is_incompatibility_page; ?>"></div>
<script> 
   var $buoop = {
      required:{i:9,f:-3,o:-1,s:-3,c:-3},
      insecure:false,
      unsupported:false,
      api:2018.06,
      reminder:0,
      no_permanent_hide: true,     
      nomessage: true,
      onshow: function(infos){
         var el = document.getElementById('incompatibility-container');
         if (el && el.getAttribute('data-compatible') == 'nope' && el.getAttribute('data-where')) {
            window.location.replace(el.getAttribute('data-where'));
         }
      }
   }; 
   function $buo_f(){ 
      var e = document.createElement("script"); 
      e.src = "//browser-update.org/update.min.js"; 
      document.body.appendChild(e);
   };
   try {document.addEventListener("DOMContentLoaded", $buo_f,false)}
   catch(e){window.attachEvent("onload", $buo_f)}
</script>
```

**Comment by dimkasta** [comment]
I am having the same issue. It seems that i:9 and i:8 is flipped to the minimum required value which is defined to 10 on the script

https://github.com/browser-update/browser-update/blob/e2aa26319b14de1ba73b88c4a6cbfeabb8fb5403/update.js#L171

And then later the set required value is flipped to the minimum, which is 10

https://github.com/browser-update/browser-update/blob/e2aa26319b14de1ba73b88c4a6cbfeabb8fb5403/update.js#L191

I changed the minimum value to 9 and now it works ok.

It really seems weird as a behavior though...
