### ISSUE TITLE
IE 9 doesn't show notification

### ISSUE THREAD

**Issue by pawan-soni** [browser-update/browser-update#406]
Windows 7 + IE 9 doesn't display a popup, I've tested this with the script on my site using Browserstack.
I have set 'test: true' even I popup didn't show up, however, it shows up properly on all the browser even in IE 10 and later.

**Comment by josselex** [comment]
Please tell mit the site where i can test it.
And what code did you use?

Am Mo., 16. Juli 2018 um 21:32 Uhr schrieb soni <notifications@github.com>:

**Comment by pawan-soni** [comment]
This is the configuration:

<script> 
var $buoop = {
    required: {i:10,f:51,o:17,s:9,c:56,e:10},    
    reminder: 0,
    reminderClosed: 1,
    test: true,
	mobile:false,
    newwindow: false,
    noclose:false,
    nomessage: false,
    jsshowurl: "//browser-update.org/update.show.min.js",
    container: document.body,
    no_permanent_hide: true,
    api: 2018.07
};

function $buo_f(){ 
 var e = document.createElement("script"); 
 e.src = "//browser-update.org/update.min.js"; 
 document.body.appendChild(e);
};
try {document.addEventListener("DOMContentLoaded", $buo_f,false)}
catch(e){window.attachEvent("onload", $buo_f)}
</script>

I got an internal site (running on VPN) so cannot share site detail.

**Comment by josselex** [comment]
If the popup does not show up even when test mode is on there has to be a serious issue. 
Did you get any error in the javascript console?

**Comment by josselex** [comment]
No more information on this issue...
closing.
