### ISSUE TITLE
Boring !!

### ISSUE THREAD

**Issue by antec74** [browser-update/browser-update#407]
Hello
I use android CM browser (cookies are on)
When connecting to "decathlon.fr ", i always have "update your browser .." but my browser is updated.
Clicking "ignore " don't stop the message "update your browser ..." it's boring !!
BTW when connecting to your site with CM Browser : no message !! it's funny !!
What can you do ?
If this situation goes on , i will answer Decathlon to remove your application from the site.
Thanks for your response.

**Comment by josselex** [comment]
Strange. Somehow your cookie must get deleted.
Anyway, I will whitelist CM browser as a niche browser not getting notified.
Also I will try to investigate the reason why your cookie does not get set
or kept.

Am Mi., 25. Juli 2018 um 09:24 Uhr schrieb antec74 <notifications@github.com

**Comment by josselex** [comment]
Yeah! I found the bug. A fix is coming today!

**Comment by josselex** [comment]
It should be fixed now. Can you please verify this?
