### ISSUE TITLE
Vue.js Issues

### ISSUE THREAD

**Issue by resourcemedia** [browser-update/browser-update#411]
Having issues with vue.js. It works on many of the older browsers. But does not on IE 9, 10, 11.
My current code:

import Vue from 'vue'

import VueBrowserUpdate from 'vue-browserupdate';

Vue.use(VueBrowserUpdate, {
    options: {
        required: {i:10,f:25,o:17,s:9,c:22},
    },
});

**Comment by josselex** [comment]
Can you point towards and example?
Does vue.js work in these old browsers at all?

**Comment by josselex** [comment]
Seems to work now. Right?
