### ISSUE TITLE
The Magento plugin does not work

### ISSUE THREAD

**Issue by vishy93** [browser-update/browser-update#423]
I am using magento 1.9.4.0 ("latest version of 1.x to date") and the Magento plugin does not work. The Javascript inserted but not message shown.

**Comment by josselex** [comment]
Can you point to a test page?
Does it even not show the message when you append "#test-bu" to the url, like explained here:
http://browser-update.org/customize.html

**Comment by vishy93** [comment]
@josselex I've amended the plugin and got it working. Shall recheck later what I did and get back

**Comment by vishy93** [comment]
@josselex I can Indeed. Shall I fork the repo?

**Comment by josselex** [comment]
Geat! Which repo?

vishy93 <notifications@github.com> schrieb am Fr., 13. Sep. 2019, 17:49:

**Comment by vishy93** [comment]
@vishy93 I haven't added the my code to github rep yet

**Comment by vishy93** [comment]
@josselex I have created a repo, see here: [https://github.com/vishy93/Browser_Update_Magento_Plugin](https://github.com/vishy93/Browser_Update_Magento_Plugin)

**Comment by josselex** [comment]
Great!
Could you write a few lines in the README.md on what it is and how you updates (really just 3 lines).

**Comment by josselex** [comment]
@vishy93 
I linked to your repo! Would be great if you could write a few lines what it is and how to install.
