### ISSUE TITLE
Warns for Edge 17 even with `e:-4`

### ISSUE THREAD

**Issue by wmertens** [browser-update/browser-update#425]
Subject says it all - normally it should only warn for Edge 14 and below…

**Comment by josselex** [comment]
Can you provide an example page?

**Comment by wmertens** [comment]
For example, https://www.cap.be/

This is the script it runs:

```js
          <script>
            var $buoop = {
              required: {
                e: -4,
                f: -3,
                o: -3,
                s: 9,
                c: -3
              },
              insecure: true,
              unsupported: true,
              style: "bottom",
              api: 2018.12
            };
            function $buo_f(e) {
              e = document.createElement("script")
              e.src = "//browser-update.org/update.min.js"
              document.body.appendChild(e)
            }
            try {
              document.addEventListener("DOMContentLoaded", $buo_f, false)
            } catch (e) {
              window.attachEvent("onload", $buo_f)
            }
          </script>
```

**Comment by josselex** [comment]
You configured to notify all unsupported browsers. And edge 17 is not supported anymore as the latest version is 18.

**Comment by wmertens** [comment]
According to https://en.wikipedia.org/wiki/Microsoft_Edge, there are
several versions that are still supported (the yellow blocks), amongst
which 15.15063, 15.16299, and 17.17134. 18 may be the latest version but it
is not the one that Microsoft's AutoUpdate sets by default…

**Comment by josselex** [comment]
Indeed. Thanks. I will fix this ASAP.

**Comment by josselex** [comment]
This is fixed since the day before yesterday.
