### ISSUE TITLE
Safari 12 erroneously marked as 'unsupported'

### ISSUE THREAD

**Issue by simonsolts** [browser-update/browser-update#427]
On Mac OS 10.14.1 Mojave, the latest version of Safari is detected as being 'out of date'.

Safari 12
on MacOS 10.14.
It is not supported by the vendor anymore.
It is not the latest version.
You can upgrade to a newer version of Safari.
Your browser is safe.
Your browser identifies itself with ("User agent string"):
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.1 Safari/605.1.15

![image](https://user-images.githubusercontent.com/12909505/50822458-ae473580-1329-11e9-9b09-089092a01070.png)

**Comment by josselex** [comment]
I now modified the dialog to show the full version of the browser.

You must have Safari 12.0.1, the latest version since December 5, 2018 is  12.0.2 fixing security holes.

**Comment by josselex** [comment]
Hm. Ok. There seems to be something wrong...

**Comment by emilycritter** [comment]
I'm also running into an issue with Safari 12 that may be related.

I still see the banner notification on both Safari 12.0 and Safari 12.0.2 with the following settings:

```
var $buoop = {
notify:{e:-1,f:-5,o:-5,s:11,c:-5},
reminder:0,
test:false,
newwindow:true,
style:"top",
insecure:"off",
unsupported:"off",
mobile:"on",
api:5
};
```
![image](https://user-images.githubusercontent.com/16456162/56909712-62ea9b80-6a6e-11e9-88d0-e872ba323baf.png)

![image](https://user-images.githubusercontent.com/16456162/56909790-8dd4ef80-6a6e-11e9-959c-c0e15b825200.png)

**Comment by josselex** [comment]
Your code is wrong. You have to write:

```
insecure: false,
unsupported: false,
mobile:true,
```
