### ISSUE TITLE
Slovenian warning message style

### ISSUE THREAD

**Issue by zsolto2004** [browser-update/browser-update#429]
Displaying the browser update warning in slovenian language does not apply default css formatting. 
(Does not take in consideration the parameter for displaying at the bottom of the page, neither)
![slovenian_header](https://user-images.githubusercontent.com/35795154/53153468-01670600-35c1-11e9-84ab-91390d8dcfb5.png)

**Comment by josselex** [comment]
It is not translated to the new text in this language. If you could help to translate the messages, then it will show up in the new style and text:

http://browser-update.org/contact.html

**Comment by josselex** [comment]
@zsolto2004 
Finally I got the translation done for Slovenian and it will now display like all other languages
