### ISSUE TITLE
Viasat Sparrow browser is no longer ignored

### ISSUE THREAD

**Issue by dlarrick** [browser-update/browser-update#431]
Greetings, 
In issue #386 you kindly included Viasat's Sparrow browser in the "niche browser" whitelist. Thanks for that, it's been working fine since then.

But recently our users are seeing the update banner on host websites again, such as https://en.parkopedia.com/ . We've taken a brief look at update.js and see sparrow still on the"niche browser ignore list -- and verified that it's there in the minified version fetched by a visit to parkopedia -- so we're unclear why this should be.

Thanks for your attention.

**Comment by josselex** [comment]
What is the current user agent of Viasat Sparrow? Did it change recently?

**Comment by dlarrick** [comment]
Our user-agent has not changed (except the underlying Chromium version). But we've discovered a bug where the user-agent is correct in http headers, but sometimes not set properly for Javascript access. Does browser-update access UA via JavaScript or headers?

**Comment by josselex** [comment]
Yes! It is only read out via Javascript.

**Comment by dlarrick** [comment]
> Yes! It is only read out via Javascript.

All right, thanks, I am closing this issue. Sorry for the noise.

**Comment by josselex** [comment]
I'm glad i could help you find the problem and maybe prevent more headache in the future.
