### ISSUE TITLE
The 0 in $buoop.required is not been parsed as lastest version

### ISSUE THREAD

**Issue by AnnAngela** [browser-update/browser-update#436]
if I set 0 in `$buoop.required`, I mean [I need the lastest version](https://github.com/browser-update/browser-update/wiki/Details-on-configuration), but [in update.js#L236](https://github.com/browser-update/browser-update/blob/39c71a6dc557286d54a48c7cdff61c879e0b9742/update.js#L236), it parsed as undefined if I didn't misunderstand.
So I suggested to change this line to
````javascript
if(!(b in required))
````
That looks good to me:

![image](https://user-images.githubusercontent.com/9762652/56902192-4ed58700-6acc-11e9-90ed-f75d130787a0.png)
----
I did consider doing it myself via pr, but I thought there must be a min version, which I don't want to make. This is why I open a issue instead of pr.

**Comment by josselex** [comment]
Oh! You're right. I'll fix it ASAP! Thanks!

**Comment by AnnAngela** [comment]
THX A LOOOOOOT
