### ISSUE TITLE
Add UMD loader

### ISSUE THREAD

**Issue by rejas** [browser-update/browser-update#443]
I am trying to incorporate your library to my project. Alas I am not able to use a bundler like  webpack or browserify.

Therefor just adding the js results in an error due to the module.exports line at the end.

Would it be an option to add a UMD factory method around it like this:

```
;(function (root, factory) {

    if (typeof define === 'function' && define.amd) {
        define(factory);
    } else if (typeof exports === 'object') {
        module.exports = factory();
    } else {
        root.browserUpdate = factory();
    }

}(this, function () {
    return $buo;
}));
```
(shamelessly copied from https://devhints.io/umdjs)

Is that something you would be willing to add? If so, I would glady create a PR for this.

**Comment by josselex** [comment]
Hi, 
I today merged #445.
Is this related to your problem? 

I would glad to add your code. I'm not yet very fluent with all these loaders so I don't really know what is does :).

**Comment by josselex** [comment]
@rejas 
I'm trying to implement this now, bat have to struggle a bit.
I got it working with your code with browserify.
But how can i use it directly with an ES6 capable browser?

**Comment by rejas** [comment]
@josselex unfortunatly the project that I tried to use it in already moved on. So there is no need for me personally anymore for this feature. But that also I means I dont have any chance to test your current state. Thanks for your work anyway!
