### ISSUE TITLE
429 Too Many Requests on first feedback submitted ever

### ISSUE THREAD

**Issue by TamaHobbit** [browser-update/browser-update#447]
I tried to use the feedback form but on clicking submit, I got a page saying I had exceeded the maximum of 6 per day, even though I have never submitted feedback before.

The feedback was basically seconding issue #233 - my browser is up-to-date according to apt-get upgrade, so I don't know this website is telling to update to the latest version of chrome, which isn't possible since I don't have it in the first place.

I would also second issue #124, and I don't understand why that one is closed because it is still an issue - detection should be done on blacklist not whitelist basis.

**Comment by josselex** [comment]
The too many requests thing is fixed now.

For the second thing I need to know which browser you are using to judge correctly.

**Comment by TamaHobbit** [comment]
Issue #233 applies to chromium, which is what I use.
