### ISSUE TITLE
Issue template broken

### ISSUE THREAD

**Issue by tmtvl** [browser-update/browser-update#449]
The issue template for wrong messages recommends going to your site, but you've put a semicolon after the protocol instead of a colon.

**Comment by josselex** [comment]
Hi!
Where did you find the broken link?

**Comment by tmtvl** [comment]
When I went to create an issue and selected "I'm a user and the message is wrong/should not appear", the URL is in the third bullet point:

```Markdown
* copy and paste here what you see on https;//browser-update.org/test.html
```

**Comment by josselex** [comment]
Thanks for reporting.
This if fixed now.
