### ISSUE TITLE
New at JS and cant get custom message

### ISSUE THREAD

**Issue by Garthgnc** [browser-update/browser-update#453]
Hi guys, apologies for such an entry level question but battling. using the standard Script file provided and it's working great (Joomla) but i want to have a custom message for IE (Not supported at all anymore)

I am not a JS person and cannot figure out where to drop the into the script
   text_for_i: {
       'msg':'Your browser ({brow_name}) is so damn old! Internet Explorer is not supported anymore.',
       'msgmore': 'Update your browser as soon as possible to use this site.'
    }

Please can someone assist with the script detail. And thanks for the plug in!

**Comment by josselex** [comment]
Hi!
Like this:
```
<script> 
var $buoop = {
    required:{e:-4,f:-3,o:-3,s:-1,c:-3},
    insecure:true,
    api:2019.10 
    text_for_i: {
        'msg':'Your browser ({brow_name}) is so damn old! Internet Explorer is not supported anymore.',
        'msgmore': 'Update your browser as soon as possible to use this site.'
    }
}; 
function $buo_f(){ 
 var e = document.createElement("script"); 
 e.src = "//browser-update.org/update.min.js"; 
 document.body.appendChild(e);
};
try {document.addEventListener("DOMContentLoaded", $buo_f,false)}
catch(e){window.attachEvent("onload", $buo_f)}
</script>
```
