### ISSUE TITLE
Ability to show message for specific browser, even if up to date

### ISSUE THREAD

**Issue by barbalex** [browser-update/browser-update#454]
**Is your feature request related to a problem? Please describe.**

Our Web-App enables some fairly complex printing. It es extremely hard to get complex printing to work over all browsers. It seems that this is where specs are simply not good enough yet. That is why our app is 100% compatible with all modern browsers - except for printing. This only works kind of well on Chromium based browsers and Safari (though even there we would like to see better specs).

I know this is not what we all want to achieve. But after loosing _lots_ of time unsuccessfully trying to get printing to work acceptably on all browsers we have given up. And having to decide between optimizing printing for Firefox or Chrome / Opera / Edge Chromium OR Safari, we decided for Chromium. Also because window.matchMedia('print') does not fire when the user prints on Firefox, see this bug which has remained open for 7 years: https://bugzilla.mozilla.org/show_bug.cgi?id=774398.

**Describe the solution you'd like**

We would like to use this tool to not only ask users to update old browsers. But also to inform them that printing will sometimes not work correctly, when they use our app with non chromium based browsers.

**Comment by southeasterntech** [comment]
I'm having a similar problem where I would like everyone using Internet Explorer to know that something will not work on that browser.

**Comment by josselex** [comment]
@southeasterntech
For internet explorer this is possible. Internet Explorer is not developed anymore, that's why it is "outdated". It's successor is Edge.
You can right now notify all internet explorer users.

**Comment by josselex** [comment]
@barbalex 
I understand your particular problem. However, we want to encourage website owners to at least support all recent versions of major browsers. That's why we do not want to allow to notify these browsers in general.

**Comment by barbalex** [comment]
O.k., I was expecting this answer
