### ISSUE TITLE
Cookie set without the 'SameSite' and 'Secure' on Chrome.

### ISSUE THREAD

**Issue by MMaicki** [browser-update/browser-update#455]
Warning from Chrome about cookie parameters. Can you fix the way your script is setting the cookie? SameSite and Secure parameters are missing and chrome will soon stop delivering your script.

**Comment by josselex** [comment]
Thanks. I will look into this.

**Comment by josselex** [comment]
This is not a problem with a browser-update.org cookie but from our provider, cloudflare.
They are working on it:
https://community.cloudflare.com/t/google-chrome-warning-about-cloudflare-cookie/123192

Apart from the warning, this does not pose a problem.

**Comment by josselex** [comment]
This cookie will be gone starting form May 10.
See:
https://blog.cloudflare.com/deprecating-cfduid-cookie/
