### ISSUE TITLE
Browserupdate flag all as bot

### ISSUE THREAD

**Issue by Rekinysukcesu** [browser-update/browser-update#456]
Hi,
I have noticed a problem with your script for several days.
For an unknown reason, all browsers have been marked as robots, so they do not display pop-ups.

Can you check it?.
Example of a page with a problem.:
https://www.soft-music.pl/

**Comment by josselex** [comment]
Thanks for reporting.
This is fixed now.

**Comment by josselex** [comment]
Fixed in 29b61971b219442d99e2c89e8dfed7f49eb37fa2
