### ISSUE TITLE
iPad OS 13 / Safari 13 (newest) is shown as outdated

### ISSUE THREAD

**Issue by frontend-biz** [browser-update/browser-update#459]
![Safari_13_iPad_OS_Error_2019-11-06](https://user-images.githubusercontent.com/1492341/68274870-81a79b80-006a-11ea-9c45-4a08f370fd1a.jpg)

**Comment by SkyhopperZH** [comment]
This is a bit embarassing ;-)

**Comment by josselex** [comment]
Thanks for reporting. Fix is coming in a few seconds.
See issue here https://github.com/juliangruber/is-mobile/issues/17

**Comment by josselex** [comment]
@frontend-biz 
Can you verify that it is fixed? (Reloading the page)

**Comment by josselex** [comment]
Used this trick for the fix:
https://stackoverflow.com/questions/58019463/how-to-detect-device-name-in-safari-on-ios-13-while-it-doesnt-show-the-correct

**Comment by frontend-biz** [comment]
![IMG_B0098B98B43D-1](https://user-images.githubusercontent.com/1492341/68316790-5482d980-00ba-11ea-9fb7-e992a1069b65.jpeg)

**Comment by frontend-biz** [comment]
Seems to work now. Thank you very much !
