### ISSUE TITLE
404 /browserstat?jsv=3.3.7

### ISSUE THREAD

**Issue by rbannat** [browser-update/browser-update#460]
https://github.com/browser-update/browser-update/blob/0be96a9ba76c97af77ba13cdde0a1b59262e3d18/scripts/update.npm.full.js#L276

new browserstat route causes issues responding with 404, e. g. //browser-update.org/browserstat?jsv=3.3.7

**Comment by josselex** [comment]
Thanks. Fixed now.
I forgot to upload the changes.
