### ISSUE TITLE
browser-update site down?

### ISSUE THREAD

**Issue by dylanvdmerwe** [browser-update/browser-update#462]
Sorry for posting on the repo, was not sure where else to post. 

I noticed that the browser-update.org site is down. Is there a reason for this? 

Impact is that sites which point to the js script on the site will no longer work. 
`//browser-update.org/update.min.js`

**Comment by josselex** [comment]
Hi,
I can't see that it's down. Is it sill the case for you?

**Comment by dylanvdmerwe** [comment]
Ah I think it's just been flagged by Adblock and AdGuard as a dodgy site, hence why it's being blocked on my side.
