### ISSUE TITLE
Latest version is broken

### ISSUE THREAD

**Issue by thgramos** [browser-update/browser-update#463]
I am using Linux and Google Chrome in latest version (78.0.3904.108). Setting required version 78 or latest for Chrome is showing the update banner. You can test this behavior with 'Try it out!' in home page.

Debugging is possible to see the required version for chrome set as '78.01'. I tried to find where in code this is set wrong but I couldn't find.

**Comment by thgramos** [comment]
I found the problem, it is in line 253 of update.js:

> required[b] = parseFloat(vs[b]) + 0.01

Since the version number is 78.0 the logic is broken.

**Comment by josselex** [comment]
What code doy you use on your site? Settis vs:{} was the old ways. This was setting the versions you want to notfiy.
Setting required: {...} is the new way ou shoud use. This sets the minimum required version.

**Comment by thgramos** [comment]
Yes, I'm using required as the parameter. You can reproduce de error with the latest Chrome version, the sample script at http://browser-update.org/ and setting Chrome to latest version required (required:{e:-4,f:-3,o:-3,s:-1,c:0}).

The latest version is now 78.0.3904.108 and the required will be 78.01, which is greater than 78.0, so it will trigger the notification.

**Comment by josselex** [comment]
@thgramos 
I cannot reproduce this. using "required": {"c":0} makes 80 as the current version is 80.

**Comment by thgramos** [comment]
I found the problem now. On my first test I used an AngularJS directive (http://github.com/tinesoft/ng-browser-update), which is no longer maintained and it was passing the versions with vs arg.

My next attempt was with the main page browser sample, and it is forcing the test mode (which is unclear in options), so I thought that the problem persisted.

Thanks for the help! I'm closing this issue.
