### ISSUE TITLE
Cookie not being set over http non-secure connection

### ISSUE THREAD

**Issue by rotavio** [browser-update/browser-update#464]
The cookie to pause or ignore the warning is not being set when we access aour site using http. Over https it works fine. We are testing using Firefox 52, and the message is always showing, on each refresh, and no cookies are being created.
Our code:
`    <script>
      var $buoop = {
        api: 2019.11,

        required: { e: 16, f: 60, o: 54, s: 11, c: 68 },
        reminder: 24,
        reminderClosed: 150,
        text: '<p>Seu navegador da web (<strong>{brow_name}</strong>) está desatualizado ou não é compatível com este site.</p><p class="info">Alguns recursos podem não funcionar ou serem exibidos incorretamente.</p><div class="buttons"><a{up_but}>Mais informações</a> <a{ignore_but}>Ignorar</a></div>',
        text_en: '<p>Your web browser (<strong>{brow_name}</strong>) is outdated or is not compatible with this site.</p><p class="info">Some features may not work or be displayed properly.</p><div class="buttons"><a{up_but}>Read more</a> <a{ignore_but}>ignore</a></div>',
        text_es: '<p>Su navegador web (<strong>{brow_name}</strong>) está desactualizado o no es compatible con este sitio.</p><p class="info">Algunas características pueden no funcionar o mostrarse incorrectamente.</p><div class="buttons"><a{up_but}>Mas informaciones</a> <a{ignore_but}>ignorar</a></div>',
        url: document.body.getAttribute('data-portal-url') + '/' + document.documentElement.getAttribute('lang') + '/browser-info',
        onshow: function(){ document.body.setAttribute('data-browser-version-msg', 'true') },
        onclose: function(){ document.body.setAttribute('data-browser-version-msg', 'false') }
      };

      function $buo_f() {
        var e = document.createElement("script");
        e.src = "//browser-update.org/update.min.js";
        document.body.appendChild(e);
      }
      try {
        document.addEventListener("DOMContentLoaded", $buo_f, false);
      } catch (e) {
        window.attachEvent("onload", $buo_f);
      }
    </script>
`

**Comment by josselex** [comment]
Sorry. I somehow missed you bugreport. Can you tell me your site URL that i can debug this?

**Comment by josselex** [comment]
@rotavio 
 Can you tell me your site URL that i can debug this?

**Comment by josselex** [comment]
This should be fixed in 36566f3c22b80edea55e1ab936e6f8f7c1f8e4b7

Can you verify that it works now?
