### ISSUE TITLE
New Edge browser supports multi-platform. Perhaps it should be recommended not only for Windows 10

### ISSUE THREAD

**Issue by vpetrusevici** [browser-update/browser-update#469]
**Is your feature request related to a problem? Please describe.**
New Edge supports many platforms, but has recommendation to install only for Windows 10.

**Describe the solution you'd like**
Add it to recommendations for other operating systems of the Windows family

**Additional context**
![image](https://user-images.githubusercontent.com/40790510/73334219-d5dea800-4274-11ea-878d-556ea3ce4ce7.png)
![image](https://user-images.githubusercontent.com/40790510/73334301-0a526400-4275-11ea-8a08-b60dbc11aad8.png)

**Comment by josselex** [comment]
It will now be offered for users of IE and older Edge on Windows >=7 and macOS. Offering it to all users will happen when they have a properly translated landing page.

**Comment by frankang** [comment]
@josselex 

It looks like Edge's homepage now displays language according to browser locales. So maybe it's time to make it available for all users.
https://www.microsoft.com/edge

**Comment by jonmnoj** [comment]
Yes they have quite a few different languages now available for the landing page
[https://www.microsoft.com/en-us/edge/worldwide](https://www.microsoft.com/en-us/edge/worldwide)
