### ISSUE TITLE
Give browser info as argument to callback onshow

### ISSUE THREAD

**Issue by joshkg** [browser-update/browser-update#470]
We handle the DOM messaging ourselves with the option `nomessage` and hooking in to the callback `onshow`.

However, there doesn't seem to be a way to know what specific browser the user has which is not supported. We would like to customize messaging per browser. 

I see the `$bu_getBrowser` is attached to the window, and that will be a workaround for now. However, it feels redundant to call `$bu_getBrowser` manually. Rather, it would be nice if the callback for `onshow` would make this object available as an argument. Thanks!

Update: opened a PR for this: https://github.com/browser-update/browser-update/pull/471

**Comment by josselex** [comment]
My suggestion would be to just add the info to the op object, where all info is now:
Just using this line in check_show(op) {...}
`var bb=op.browser=$bu_.get_browser(op.override_ua);`

Main advantage is that i do not change the api and its simpler!

Is this ok for you?

**Comment by joshkg** [comment]
@josselex that works, I'll update

**Comment by josselex** [comment]
This is available now!
