### ISSUE TITLE
iOS 12.4.5 false positive

### ISSUE THREAD

**Issue by byteasc** [browser-update/browser-update#472]
iOS 12.4.5 was released on January 28th and it is causing the update alert to popup for users.

![image](https://user-images.githubusercontent.com/10793868/73700361-fd39d880-46ab-11ea-8f8c-047c8681c3ff.png)

![image](https://user-images.githubusercontent.com/10793868/73700366-0034c900-46ac-11ea-921b-b3883bf27759.png)

12.4.5 is the latest available for phones that do not support iOS 13 so it shouldn't be failing browser support check. Our script supports back to Safari 8. We are not using latest API though, as we haven't had a reason to update the actual script implementation

**Comment by josselex** [comment]
Usually it should only show up on iphones that can be updated. I implemented a complicated detection for this.
I wil have a look into this.

**Comment by byteasc** [comment]
Thank you! For the time being we have turned off browser alerts, since we do not allow them to close them across any browser, due to nature of software and all

**Comment by josselex** [comment]
It should be fixed now and do not notify the iphone 6 anymore
