### ISSUE TITLE
Facebook - Inapp browser

### ISSUE THREAD

**Issue by paulincai** [browser-update/browser-update#482]
**Is your feature request related to a problem? Please describe.**

I find it very hard to locate any information about this troublesome browser. This refers to the browser in which links open inside the Facebook mobile app.

I can see that Facebook browser in IOS behaves differently than the one in Android (9). In fact in IOS I have no issue while in Android 9 my website is not rendered failing with an error related to ES modules which tells me that the FB inapp browser on Android doesn't support (some) modern features.

Does that browser fall into the scope of this package?

**Comment by josselex** [comment]
Sorry, I do not habe any information on this browser. And usually browsers like this should be ignored by this script, because the user cannot update the browser.
