### ISSUE TITLE
missing ) after argument list (https://browser-update.org/update.min.js#3)

### ISSUE THREAD

**Issue by tommedema** [browser-update/browser-update#483]
<img width="1208" alt="Screen Shot 2020-03-06 at 8 13 00 PM" src="https://user-images.githubusercontent.com/331833/76136486-ea862c80-5fe6-11ea-98d7-558ff57edb16.png">

Please provide 
* the full code you are using 

```
<script> 
      var $buoop = {required:{e:-4,f:-3,o:-3,s:-1,c:-3},insecure:true,api:2020.02 }; 
      function $buo_f(){ 
       var e = document.createElement("script"); 
       e.src = "//browser-update.org/update.min.js"; 
       document.body.appendChild(e);
      };
      try {document.addEventListener("DOMContentLoaded", $buo_f,false)}
      catch(e){window.attachEvent("onload", $buo_f)}
    </script>
```

* an example site where the problem can be reproduce

https://app.usebubbles.com/

* the browser, operating system and device where the bug appears

<img width="559" alt="Screen Shot 2020-03-06 at 8 12 01 PM" src="https://user-images.githubusercontent.com/331833/76136476-c9bdd700-5fe6-11ea-95eb-bcb353699e86.png">

User agent:

```
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
```

**Comment by josselex** [comment]
I cannot reproduce the error on your site. I tried last week and now.

**Comment by tommedema** [comment]
Ok, will close it then
