### ISSUE TITLE
New to JS, need help

### ISSUE THREAD

**Issue by mbloch06** [browser-update/browser-update#485]
Hi:  I want to insert this into the script:

text_for_i: {'msg':'Internet Explorer is not supported on this site.'}

This is what I did below, but when I add it, the script doesn't work.  What am I doing wrong, what is the correct format?  I would like it to show EVERY time a person comes to the site using Internet Explorer.
thanks!

<script>
var $buoop = {required:{e:-6},unsupported:true,mobile:false,api:2020.03 };
text_for_i: {'msg':'Internet Explorer is not supported on this site.'},
reminder: 0,
function $buo_f(){
 var e = document.createElement("script");
 e.src = "//browser-update.org/update.min.js";
 document.body.appendChild(e);
};
try {document.addEventListener("DOMContentLoaded", $buo_f,false)}
catch(e){window.attachEvent("onload", $buo_f)}
</script>

**Comment by josselex** [comment]
You missed a `}` and used a `;` where a `,` was needed instead.

Use this:
```
<script>
 var $buoop = {required:{i:12,c:1,f:1,s:1,e:1,o:1},unsupported:true,mobile:false,api:2020.03 },
 text_for_i: {'msg':'Internet Explorer is not supported on this site.'}, reminder: 0
}
function $buo_f(){ var e = document.createElement("script"); e.src = "//browser-update.org/update.min.js"; document.body.appendChild(e); }; 
try {document.addEventListener("DOMContentLoaded", $buo_f,false)} catch(e){window.attachEvent("onload", $buo_f)} 
</script> 
```

I also changed your code to only notify internet explorer using `i:12`
