### ISSUE TITLE
vue.js Version is outdated

### ISSUE THREAD

**Issue by thmsnhl** [browser-update/browser-update#486]
The version of vue-browserupdate, that is linked in the plugins section on browser-update.org is outdated and creates frustration because it does not match the expected behavior described in the documentation.  Also the author does not respond to open issues. 

Because of this, we forked the project, fixed an existing issue and updated the dependencies: https://www.npmjs.com/package/@sum.cumo/vue-browserupdate 

Please update the link to our project, so that the vue.js version is also working correctly.

**Comment by josselex** [comment]
Thank you very much for taking car of it. I updated the link! This is awesome!
