### ISSUE TITLE
Browser warning messes up application positioning logic

### ISSUE THREAD

**Issue by tommedema** [browser-update/browser-update#487]
I've created a video of the issue [here](https://app.usebubbles.com/242ea659-121d-443b-a314-ad473a3bc4bc).

Basically, the modal pushes everything down, which can cause issues when applications use the cursor pageX and pageY position on mouse events.

Demo: try moving a bubble at https://app.usebubbles.com/4f112ea8-b668-411e-abe9-eae13637a22e#test-bu

**Comment by josselex** [comment]
Hi!

There are two easy solutions:

use the option
shift_page_down:false

or position the notification on the bottom or on the side
