### ISSUE TITLE
iOs 12.3 wrongly reported

### ISSUE THREAD

**Issue by OZZlE** [browser-update/browser-update#490]
I want to allow latest two major versions so I selected:

<img width="511" alt="Skärmavbild 2020-04-20 kl  14 45 11" src="https://user-images.githubusercontent.com/893783/79753029-8bba0f80-8315-11ea-9570-77e1846d0433.png">

    <script> 
    var $buoop = {required:{e:-2,f:-6,o:-1,s:-1,c:-6},insecure:true,api:2020.04 }; 
    function $buo_f(){ 
     var e = document.createElement("script"); 
     e.src = "//browser-update.org/update.min.js"; 
     document.body.appendChild(e);
    };
    try {document.addEventListener("DOMContentLoaded", $buo_f,false)}
    catch(e){window.attachEvent("onload", $buo_f)}
    </script>

Latest two major versions of iOs is 13.4 and 12.3, 12.4 is only supported on a very small subset of devices. Using browser stack I couldn't find any iPhone supporting it (but they do support 12 and 13). https://en.wikipedia.org/wiki/IOS_version_history#iOS_12

I even change to allow v.11 but I still get the notification on all 12.x versions - haven't been able to test 12.4 even..

**Comment by josselex** [comment]
Thanks for the information. I will look into this tomorrow.

**Comment by josselex** [comment]
I now list 12.3 as the latest insecure version.
You got the notification because <12.4 was marked as insecure and that's why settint to version 11 did not work.

Please check if it now works for you.
