### ISSUE TITLE
For npm usage, yarn/npm test fails due to a bug inside update.npm.full.js:  "TypeError: Cannot read property 'indexOf' of undefined"

### ISSUE THREAD

**Issue by trisnoc** [browser-update/browser-update#498]
Hi,
After I did "npm install browser-update --save" and did a yarn test on my front-end project which uses browser-update, I'm getting this error:

**● Test suite failed to run
  TypeError: Cannot read property 'indexOf' of undefined
   at $buo (packages/core/dist/webpack:/packages/core/node_modules/browser-update/update.npm.full.js:317:1)**

Line 317 of update.npm.full.js is this:

**op.already_shown=document.cookie.indexOf("browserupdateorg=pause")>-1 && !op.ignorecookie;**

Therefore, it seems that "document.cookie" is undefined and needs to be initialized to something before being used.
Can anyone look into resolving this bug?

Thanks.

**Comment by josselex** [comment]
Hi,
What is your use case? What tests are you running. I could detect the test scenario and det the cookie.
