### ISSUE TITLE
The Cookie needs to set SameSite

### ISSUE THREAD

**Issue by ellenhutchings** [browser-update/browser-update#500]
Since the [February Chromium update](https://blog.chromium.org/2020/02/samesite-cookie-changes-in-february.html) the Browser update cookie provides an error.

It should be updated

**Comment by josselex** [comment]
This should be fixed now.

**Comment by ellenhutchings** [comment]
It's not. This is after clearing the cache:
![image](https://user-images.githubusercontent.com/4345441/92343495-c3cdaf00-f078-11ea-9c87-6f8369fc73b7.png)

**Comment by josselex** [comment]
These cookies are only set when you visit the browser-update.org site. This is not set by the script, so normally this error should not show up if you just see the bar.

**Comment by josselex** [comment]
Also the cookie __cfduid will be gone by May 10.
See:
https://blog.cloudflare.com/deprecating-cfduid-cookie/
