### ISSUE TITLE
Having French browser causes the script click to update browser to fail

### ISSUE THREAD

**Issue by berickus** [browser-update/browser-update#502]
To reproduce:
- Install e.g. Firefox 75 in French (https://ftp.mozilla.org/pub/firefox/releases/75.0/mac/fr/)
- Go e.g. to https://abo.lematindimanche.ch/ and click Mettre à jour le navigateur

See url location: https://abo.lematindimanche.ch/#https://browser-update.org/update-browser.html3.3.22:abo.lematindimanche.ch

Does not work every time. But was able to reproduce a couple of times.

Found by APM tool.

**Comment by josselex** [comment]
I'm trying to reproduce it. 
I think it's not on your site anymore, so I can't test.

Can you send me your configuration? (var $buoop = ...)

**Comment by berickus** [comment]
We use the standard config from the website. Straight forward.

**Comment by josselex** [comment]
I tried to reproduce it, but can't. It may be an issue with your sepcific site. However I cannot find the script on your site.

**Comment by berickus** [comment]
Hi @josselex, thanks for checking again. I just tried it again and was able to reproduce and screencast it. I used French version of Fireforx 75 (https://ftp.mozilla.org/pub/firefox/releases/75.0/mac/fr/) vanilla installation.

[browser-update-issue.zip](https://github.com/browser-update/browser-update/files/5333897/browser-update-issue.zip)

**Comment by josselex** [comment]
The Problem seems to be with your code:
Some part of your CMS adds this event to the `<a>` element

```
function(e) {
  e.preventDefault();
  var anchor = $(this).attr("href").replace("#", "");
  if (typeof history.pushState !== "undefined") {
    history.pushState(null, null, "#" + anchor);
  }
  $("#navbar").removeClass("in");
  $('body,html').animate({
    scrollTop: $("#" + anchor).offset().top - 90
  }, 667.666);
}
```
It messes with the link and replaces the # there.

To circumvent this problem you can change the url of the link to not have a # in it.

For this you have to add this option to the script configuration:
url:"https://browser-update.org/update-browser.html"
