### ISSUE TITLE
Why is brave always the top suggestion?

### ISSUE THREAD

**Issue by codl** [browser-update/browser-update#506]
Why is brave browser the top suggestion for updating, higher than the browser that the user is currently using, for every platform, even ones that don't run brave at all? It's even considered a "niche" browser by the script itself.

I hate to be cynical but did some money change hands?

**Comment by josselex** [comment]
There are now a few changes:
Brave is not in the fourth spot and firefox in the first (before Edge), as I think Firefox should have the most support, as it is completely open source and run by  a foundation.

Brave is indeed now only shown on supported systems, thanks for pointing out.

Indeed brave is sponsored, as you can also see that is shows up in the area marked with "ads" on the site.
Now if Edge is shown  a small remark "sponsored" is shown to clarify.
