### ISSUE TITLE
Microsoft Teams desktop app

### ISSUE THREAD

**Issue by flexray** [browser-update/browser-update#509]
Teams Desktop app requests as:
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Teams/1.3.00.24755 Chrome/69.0.3497.128 Electron/4.2.12 Safari/537.36`

This shows "old browser" as Chrome/69 appears. Could we fix that and recognize `Teams/1.3.00` ?

**Comment by flexray** [comment]
Well this also required `insecure:false,unsupported:false`

**Comment by josselex** [comment]
Qt is now ignored. I think I will add an information for outdated QT like:
"You are using an old embedded browser (QTWebengine). In case this site does not work, use your normal browser".

What do you think?

**Comment by flexray** [comment]
Perfect!
