### ISSUE TITLE
Can't target IE 11

### ISSUE THREAD

**Issue by picks44** [browser-update/browser-update#510]
Hello all,
I've just implemented the plugin (through Webpack) but when trying it on IE 11 (which I want to target), it doesn't show.
Here is my JS code

```
/* BROWSER-UPDATE */
import browserUpdate from 'browser-update';

browserUpdate({
    required: {
        e: -4,
        i: 999,
        f: -3,
        o: -3,
        s: -1,
        c: -3,
    },
    reminder: 24,
    reminderClosed: 150,
    insecure: true,
    unsupported:true,
    api: 2020.10,
    test: false
});

```

Can anyone help? IE version is 11.1083.18362.0....

**Comment by christinemcclure** [comment]
I'm also seeing this problem. We have one particular database that still relies on IE to work properly, so I need to check for it.

**Comment by picks44** [comment]
Up?

**Comment by josselex** [comment]
This should work as expected.
Did you check this:
https://github.com/browser-update/browser-update/wiki/Test-the-notification

**Comment by picks44** [comment]
Thanks, it is working now for some reason, maybe I had the cookie set up and didn't clear it...
