### ISSUE TITLE
Support for QtWebEngine

### ISSUE THREAD

**Issue by grzchr15** [browser-update/browser-update#511]
**Is your feature request related to a problem? Please describe.**

QT-Browser send this browser agent:
"Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.3 Chrome/69.0.3497.128 Safari/537.36"
and gets currently detected as Chrome 69

**Describe the solution you'd like**
Get regcognized as QT-Browser

https://doc.qt.io/qt-5.12/qtwebengine-overview.html says

Qt WebEngine Core Module

The Qt WebEngine core is based on the Chromium Project. Chromium provides its own network and painting engines and is developed tightly together with its dependent modules.

Note: Qt WebEngine is based on Chromium, but does not contain or use any services or add-ons that might be part of the Chrome browser that is built and delivered by Google. You can find more detailed information about the differences between Chromium and Chrome in this overview that is part of the documentation in the Chromium Project upstream source tree.

This version of Qt WebEngine is based on Chromium version 69.0.3497.128, with additional security fixes from newer versions.

**Comment by josselex** [comment]
Qt is now ignored. I think I will add an information for outdated QT like:
"You are using an old embedded browser (QTWebengine). In case this site does not work, use your normal browser".

What do you think?
