### ISSUE TITLE
Change browser update link

### ISSUE THREAD

**Issue by 10Meisterbaelle** [browser-update/browser-update#519]
**Is your feature request related to a problem? Please describe.**
It annoys me that I have to link to a site with ads, I'd prefer to host the browser update website myself.

**Describe the solution you'd like**
A css setting so you can change the link

**Additional context**
There is a "url" field but it doesn't seem to do anything.

**Comment by josselex** [comment]
Hi,
I will look into the issue with the link and fix it.

**Comment by s4muel** [comment]
play with the `jsshowurl` option. the default is set to: http://browser-update.org/update.show.min.js, you can create your own one and link to whatever you like

**Comment by josselex** [comment]
@10Meisterbaelle 
Actually, the url option works.
`var $buoop = {"url":"https://example.com"}`

Test it here:
https://browser-update.org/test/bar.html?#{%22url%22:%22https://test.de%22}

**Comment by 10Meisterbaelle** [comment]
> @10Meisterbaelle 
> Actually, the url option works.
> `var $buoop = {"url":"https://example.com"}`
> 
> Test it here:
> https://browser-update.org/test/bar.html?#{%22url%22:%22https://test.de%22}

Where do I have to configure this?

**Comment by josselex** [comment]
> Where do I have to configure this?

This is for example could be the code you use to embed:
```html
<script> 
var $buoop = {
   required:{e:-4,f:-3,o:-3,s:-1,c:-3},
   "url":"https://example.com",
   insecure:true,
   api:2021.03 
}; 
function $buo_f(){ 
 var e = document.createElement("script"); 
 e.src = "//browser-update.org/update.min.js"; 
 document.body.appendChild(e);
};
try {document.addEventListener("DOMContentLoaded", $buo_f,false)}
catch(e){window.attachEvent("onload", $buo_f)}
</script>
```
