### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ','

### ISSUE THREAD

**Issue by mtjoseph** [browser-update/browser-update#526]
The following error is thrown in debug console on FF 87.0, Chrome 89.0.4389.114, and Brave v1.22.70. Wordpress v5.5.1. wp-browserupdate v4.3.1

I removed all plugins for my site and the error still occurs. 

The debug console shows this line with error 'Uncaught SyntaxError: Unexpected token ','
var $buoop = {required:{e:,f:,o:,s:,c:},test:false,newwindow:true,style:"",insecure:,unsupported:,mobile:,shift_page_down:,api:2021.03};

The source code links to this code block:
<script type="text/javascript">
var $buoop = {required:{e:,f:,o:,s:,c:},test:false,newwindow:true,style:"",insecure:,unsupported:,mobile:,shift_page_down:,api:2021.03};

function $buo_f(){
var e = document.createElement("script");
e.src = "//browser-update.org/update.min.js";
document.body.appendChild(e);
};
try {document.addEventListener("DOMContentLoaded", $buo_f, false)}
catch(e){window.attachEvent("onload", $buo_f)}
</script>

**Comment by josselex** [comment]
This seems to be an arrow with the Wordpress-Plugin.
Here the values are missing: `{e:,f:,o:,s:,c:}`.
Sould be somthing like `{e:11,f:77,...}`
Can you contact the author of the Wordpress plugin or check if there is an error in your wordpress installation?
