### ISSUE TITLE
Current Browsers List has wrong version

### ISSUE THREAD

**Issue by codertushar** [browser-update/browser-update#532]
Current Browser versions in the API & website are:
Chrome: 90
Edge: 90
Opera: 76
Firefox: 89

Which is wrong. In actual, latest versions are 1 version ahead of this API is returning.
How often this data is updated? Once in a month or once in 3 months? & Is it done manually or automated process?
![image](https://user-images.githubusercontent.com/59651629/124907073-5fb3a880-e005-11eb-9167-eeae75f837e2.png)

This results to wrong expectation.
var $buoop = {required:{e:-2,f:-2,o:-2,s:-1,c:-2},insecure:true,api:2021.07 }; 

If I expect my browser to be maximum 2 versions older than latest but because of this old data it will come to those users who are using browsers 3 versions older.

Also, **npm version** has more old data than using above way as it is using older API internally.

**Comment by josselex** [comment]
Thanks.
This is fixed in e4e2a9ebafed4101c8362a37d66938596be072d0
The List ist usually updated every 1-2 months.
