### ISSUE TITLE
Include `update.show.js` with NPM package

### ISSUE THREAD

**Issue by RentecTravis** [browser-update/browser-update#546]
**Is your feature request related to a problem? Please describe.**
`update.npm.js` lets users who don't need the update notice avoid downloading the code to display it. If you want to avoid a request to a third-party URL for the display code, you can use the configuration option `jsshowurl`. If you just want to self host the same code `browser-update` uses you need to manually copy and paste the source code for `update.show.js` from the `browser-update` repo.

**Describe the solution you'd like**
Include `update.show.js` in the NPM package to facilitate self-hosting all JS necessary.

**Comment by josselex** [comment]
Indeed is seems that update.show,js is not in the package, although it should be there. Thanks for pointing that out. Will be fixed.
