### ISSUE TITLE
Old browser versions are being identified as the latest version 

### ISSUE THREAD

**Issue by skopekreep** [browser-update/browser-update#547]
Opera 82 is the latest version (currently), and this test was run in BrowserStack using Opera 74.  The banner does not show, although it should.  It seems to be related to the value of is_latest being incorrectly set to true.

Results from https://browser-update.org/test.html

Browser-Update.org
An initiative by websites to inform users to update their web browser
Identification
User-Agent-String (HTTP Header):
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36 OPR/74.0.3911.75

User-Agent-String (Javascript):
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36 OPR/74.0.3911.75

Detection
Detected Browser as (Javascript):
Opera 74

Browser (Header):
Opera 74

System (Header):
Windows 10

Language
Lang (HTTP Header):
en-US,en;q=0.9

Lang (Javascript):
en

More
{"cont": "NA", "country": "US", "ip": "10.0.1.68", "ip3": "162.158.255.119"}
Javascript detection details
{
  "llfull": "en-us",
  "ll": "en",
  "domain": "//browser-update.org",
  "apiver": -1,
  "jsv": "3.3.35",
  "required": {
    "e": 17,
    "i": 11,
    "c": 92,
    "f": 90,
    "s": 13.1,
    "ios": 10,
    "samsung": 9.9,
    "o": 77,
    "o_a": 62,
    "y": 20.4,
    "v": 2.6,
    "uc": 13,
    "a": 535
  },
  "reminder": 168,
  "reminderClosed": 168,
  "pageurl": "browser-update.org",
  "newwindow": true,
  "test": false,
  "ignorecookie": false,
  "reasons": [],
  "hide_reasons": [
    **"is latest version of the browser"**
  ],
  "browser": {
    "n": "o_a",
    "v": 74,
    "t": "Opera 74",
    "no_device_update": false,
    "available": {
      "c": "95",
      "f": "93",
      "s": "14.1.2",
      "e": "94.0.992.50",
      "i": "94.0.992.50",
      "ios": "13.3",
      "samsung": "15.0.2",
      "o": "80",
      "e_a": "93",
      "o_a": "65",
      "y": "21.9.1",
      "v": "4.3",
      "uc": "13.3.8"
    },
    "other": false,
    "embedded": false,
    "mobile": false,
    "discontinued": false,
    "engine": "c",
    "fullv": "74.0.3911.75",
    **"is_latest": true,**
    "is_supported": true,
    "vmaj": 74,
    "is_insecure": false,
    "engine_version": 88
  },
  "is_below_required": false,
  "notified": false,
  "already_shown": true
}
Install the browser update notification on your site
List of Webbrowsers
Insecure browser versions
 
What is my webbrowser?
Statistics
Customize and test
 
About the Project
Blog
Contact

**Comment by skopekreep** [comment]
It appears that in 
```
var pats=[
...
["OPR.VV","o_a",'c'],
...
]
```
any user agent with the prefix OPR will be interpreted as Opera for Android (o_a).  However, the user agent from the desktop page (details in the OP) clearly starts with OPR as well.  

`ua= Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36 OPR/74.0.3911.75`

For o_a, the value is 65 in ` this.vsakt = {c:"95",f:"93",s:"14.1.2",e:"94.0.992.50",i:"12",ios:"13.3",samsung:"15.0.2",o:"80",e_a:"93",o_a:"65",y:"21.9.1",v:"4.3",uc:"13.3.8"};`

This is why the Opera version of 74 appeared to be current since the check is whether the actual version is >= 65.  Had the UA been identified as desktop Opera (o) the comparison would have been with 80, and 74 is not <= 80 so is_latest would have been false and the banner would have displayed.

This short article _**may**_ have something to do with this, but given its age I'm skeptical.

**Comment by josselex** [comment]
Thanks for pointing it out. I corrected the detection of opera desktop.
