### ISSUE TITLE
Current Browser Versions?

### ISSUE THREAD

**Issue by ForbiddenEra** [browser-update/browser-update#551]
So I was hoping that this somehow used some sort of auto updating or remote resource for the currently updated browser versions.

The website http://browser-update.org/ shows that the current versions of Chrome and Firefox for example are <100; they have been >100 for a bit now.

While this tool seems great, it almost feels pointless if it's not auto-updating with browser releases and this can be even worse potentially if you're self-hosting if they're hard coded in the script?

**Comment by mtbpm** [comment]
As of today http://browser-update.org/ lists the following versions as current:

Edge 118
Firefox 120
Safari 16
Chrome 119

Which is wrong, the current versions are:

Edge 123
Firefox 124
Safari 17
Chrome 123

Can you please update this, so that the current versions are correct?

**Comment by josselex** [comment]
Updated the versions.
The versions are manually updated every 1-3months. I tried auto-updating but it makes more sense to manually check that everything is right. I think it should be more prioritized to not have false positive notifications instead of being up to date to the very day.
