### ISSUE TITLE
Edge Version Issue

### ISSUE THREAD

**Issue by ForbiddenEra** [browser-update/browser-update#552]
The generated code on the website provides the browser version as an integer, so, if using 'current version', it supplies a 0 for each version, such as 

```
required:{e:0,f:0,o:0,s:0,c:0},
```

The code that does the check, at least for edge, seemingly interprets this as false and uses the default; when I specify `0`, I get back `17` in the callback, if I specify `-1`, I get `101` (I've already updated my local sources current versions, with current being `102` at time of writing, `101` is the expected result for `-1`).. now, if I specify it as `'0'` (passing a string instead) it doesn't get evaluated as `falsey` and works.

**Comment by josselex** [comment]
Indeed there is an error for Edge. I will fix this.
