### ISSUE TITLE
Chrome Mobile 111

### ISSUE THREAD

**Issue by olivier-voutat** [browser-update/browser-update#570]
Hello,

I'm testing Browser-Update with our site in mobile using BrowserStack.

The configuration that I set is:

var $buoop = {
    required: {
        c: -6,
        e: -6,
        f: -6,
        o: -6,
        s: -1,
        samsung: -6
    },
    reminder: 0,
    reminderClosed: 72,
    //test: true,
    insecure: true,
    unsupported: true,
    api: 2023.05,
    url: getBrowserUrl(),
    text: textEnglish,
    text_fr: textFrench,
    text_de: textGerman,
    text_it: textItalian
};

But using Chrome Mobile 111 the message shows up...
![image](https://github.com/browser-update/browser-update/assets/4015741/18991ab3-c7b8-4e0e-ae91-73e13829da66)

A bug ?
Thanks for your help.

**Comment by olivier-voutat** [comment]
weird. It is gone...

**Comment by olivier-voutat** [comment]
na, network configuration. Wasn't connectig to browser-update.org. Problem is still here...

**Comment by olivier-voutat** [comment]
some extra information:
![image](https://github.com/browser-update/browser-update/assets/4015741/005c1896-5305-4458-ae5a-c32cd0a06076)

**Comment by josselex** [comment]
It is notified because of your configuration "unaupported:true"

Oliver Voutat ***@***.***> schrieb am Mo., 15. Mai 2023,
13:28:

**Comment by olivier-voutat** [comment]
Oh, ok. Thanks. I thougth that unsupported was related to other browsers not listed in the required list.

So it is other browsers and versions unsupported by the vendor ?
