### ISSUE TITLE
Waterfox G5 seems to be detected as Firefox 102 standard (not ESR)..

### ISSUE THREAD

**Issue by JohanPirlouit** [browser-update/browser-update#574]
Hi everyone,

Is your support of Waterfox updated as the browser has changed a lot last years (G3, G4 and now G5 series)? It is now based on the latest ESR version of Firefox and its last version (WF G5.1.8) is based on Firefox 102.12esr...

The old Waterfox 56 is now called "Waterfox Classic" and it now seems now to be abandoned: its last version is 2022.11 and can be recognized as FF 56.6...

Actual WF web page > https://www.waterfox.net/
"Classic" web page > https://github.com/WaterfoxCo/Waterfox-Classic/

Also, can you please update your webpages considering the actual Waterfox G5?

Best regards,
Johan

**Comment by josselex** [comment]
this should ne fixed now as Firefox 115 ESR is now detected correctly as ESR
