### ISSUE TITLE
Different browser versions between scripts

### ISSUE THREAD

**Issue by louischristner** [browser-update/browser-update#575]
Hello,

I recently added browser-update through npm to a project, but I am currently having an issue with the browser versions in which the notification appears.

I'm using the following configuration and the notification is not displayed on Chrome 108 for example:
```js
{
  required: {
    a: 114,
    c: 109,
    e: 112,
    f: 102,
    ios: 15.6,
    o: 98,
    o_a: 73,
    s: 15.6,
    samsung: 20,
    uc: 13.4
  },
  insecure: true,
  unsupported: false,
  api: 2023.07,
  text: '...',
  no_permanent_hide: true,
  reminder: 24,
  reminderClosed: 24
}
```

By looking at the code, I have found in [update.npm.full.js](https://github.com/browser-update/browser-update/blob/master/update.npm.full.js) the object [`vsakt`](https://github.com/browser-update/browser-update/blob/7b9e2e9eea656fd802293c486cc8e86c5f7521ce/update.npm.full.js#L8C10-L8C15) containing browser versions. I also found in [update.min.js](https://browser-update.org/update.min.js) the same object but with different browser versions.

Is there a reason for the differences of versions in the two scripts ?

**Comment by josselex** [comment]
You are right, this should be the same and be fixed now.

**Comment by louischristner** [comment]
Thank you for resolving this issue. Are you considering upgrading the package version on npm?
