### ISSUE TITLE
Using 'let' or 'const' instead of 'var'

### ISSUE THREAD

**Issue by asprunger** [browser-update/browser-update#577]
Dear Browser-update Team,

I hope this message finds you well. We would like to extend our gratitude for your continued dedication to developing and maintaining your JavaScript plugin. Recently, our scanning tool, SonarQube, had the opportunity to review the JavaScript code within your plugin, and we have an important observation to share.

Upon analysis, we noticed that a substantial number of JavaScript variables in your plugin are declared using the 'var' keyword. We wish to draw your attention to the fact that contemporary best practices in JavaScript development recommend using 'let' or 'const' instead of 'var' for variable declarations.

Here's the primary concern:

Variables declared with 'var' have a wider scope than 'let' or 'const.' This means they can potentially be modified unexpectedly, leading to unintended consequences or even security vulnerabilities. By using 'let' or 'const,' you can have better control over the scope and behavior of your variables, reducing the risk of unintended changes to your data.

We believe that addressing this issue can help enhance the overall security and maintainability of your JavaScript plugin. While the presence of 'var' declarations alone may not immediately result in a security breach, it is considered a best practice to use 'let' or 'const' to minimize the risk of security vulnerabilities.

We kindly ask if you have plans to address this matter in your JavaScript plugin and if there is a timeline for making these changes. We understand that refactoring code can be a significant undertaking, but it can lead to a more robust and secure codebase in the long run.

Best regards,

Alec

**Comment by josselex** [comment]
Brower-update is meant to inform people of outdated browsers to update. Therefore we are looking to be compatible with the widest range of old browsers. let and const is not supported by e.g. IE 10 or 11.
